### ISSUE TITLE
DVBC as Input 

### ISSUE THREAD

**Issue by Sammy990** [SeydX/homebridge-bravia-tvos#1]
Is it in any way possible to define DVBC or any other digital inputs to be listed in the inputs list?

Thanks

**Comment by SeydX** [comment]
Hey yes it is possible, i will add more options in a further version

I will add this in my todo list

**Comment by SeydX** [comment]
Adde in v1.1. (a95df330de8708c0fc370654a51f33ae54d4fbb4)

closed.
