### ISSUE TITLE
OK button on native Apple remote does not work as expected

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#10]
Hi,

I am using the latest plugin version on Homebridge latest version. It is working just fine except for the OK button on the Apple native remote.

When on the Android TV home menu, it does not act as the OK button but rather like the EPG one on the remote.

I am using Android TV on a Sony Bravia AF9.

![img_b1ff2f9034b3-1](https://user-images.githubusercontent.com/4128333/52494951-9cc6a700-2bcf-11e9-9558-5244cc647c4e.jpeg)

**Comment by SeydX** [comment]
Oh it seems that i have put a wrong command for OK, will fix this on v2 (currently in work)

**Comment by bxlouis** [comment]
Ok thanks! Keep the good job going!
I just found out that it was triggering the Digital/Analog key, not the EPG one.

**Comment by bxlouis** [comment]
@SeydX also, would it be possible to remap the "Exit" button to the tv remote's "Home" button? It seems that in the current version, the Exit button uses the same key as the "Back" button.

When browsing Netflix (preinstalled by Sony with tv remote with Netflix button), the only way to quit the app is through the "Home" button on the tv remote. On the current version, the Exit button does exactly the same as the "Back" one.

**Comment by SeydX** [comment]
"OK" Button should work as expected now, will look for the "Exit" button now
