### ISSUE TITLE
Issue with "Command" option

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#100]
I noticed what seems to be a bug in the Home app when adding any type of "command" in the config.
Instead of displaying the regular input selector, the accessory just displays the "On/Off" button and all the entries are listed as "On" or "Off" at the top of the details view.

![IMG_4373](https://user-images.githubusercontent.com/4128333/99905759-224b1680-2cd3-11eb-946a-b96c2624f014.PNG)

Also, all input are listed as different accessories in the TV details. I would expect that the Command is added to the regular input selector, like an app or an HDMI input.

![IMG_4374](https://user-images.githubusercontent.com/4128333/99905765-2aa35180-2cd3-11eb-9148-0e00f8709994.PNG)

**Comment by SeydX** [comment]
@bxlouis 

just force close the home app and reopen it. Should fix it

**Comment by bxlouis** [comment]
All right, I had to force close multiple times but it finally came back to normal.
Thanks @SeydX
