### ISSUE TITLE
Input and Application buttons not working

### ISSUE THREAD

**Issue by Fofer** [SeydX/homebridge-bravia-tvos#101]
Hi, I have v4.1.1 working great, I am able to turn my Sony TV (Bravia XBR-65X750D) on and off and adjust the volume via HomeKit.  I love it!  

I just added **HDMI 2** as a TV input, and since this version of the plug-in successfully scanned for installed apps on my Sony, I added **VUDU** as an application too.  The buttons show up in HomeKit.  However, pressing them doesn't do anything.  They don't toggle off and they don't launch VUDU or switch to HDMI 2.  As far as I can tell, nothing's happening.

My Sony is a  homebridge-bravia-tvos 4.1.1 is setup using the Pre-Shared Key method. I left App Name and App UUID blank because I didn't know what to put there and the documentation seems to imply those are only necessary for the PIN authentication method.

Any pointers appreciated.  Thanks so much!

**Comment by SeydX** [comment]
Hey @Fofer 

Yes appName and appUUID is only for PIN authentication.

I assume you have added the inputs via new custom ui?

Can u post your config.json pls

**Comment by Fofer** [comment]
SOLVED:  I force quit the Home app and now these two options instead appear within a menu, inside the Sony TV button, and not as separate buttons in the Home app interface.

And this time, more importantly... they work.

**Comment by SeydX** [comment]
Ah nice. Yes due to the reason that TVs are now „external accessories“ - the home app needs to be forced close after every hb restart to rearrange/link the inputs to the tv. I think its a bug in apple home, every tv plugin that expose the tv as a external accessory has the same bug.

But glad thats work now 👍🏼 

Closing this issue

**Comment by Fofer** [comment]
Thank you SeydX. You rock!
