### ISSUE TITLE
How to get to AndroidTV Home Screen?

### ISSUE THREAD

**Issue by Fofer** [SeydX/homebridge-bravia-tvos#102]
My default streaming device is on HDMI 2 and I leave it there most of the time.  Sometimes I do have to get to the AndroidTV interface for TV settings though, to bounce around the Home screem, or for browsing the Google Play Store, or launching an app that's only installed on the TV.  

How do I switch to that?  It's not on the Inputs list.  And I don't see the "Home Screen" as an available app.   I'm talking about the screen you see whan you tap the "Home" button on the original Sony remote.  Can a command to get there be added to HomeKit?

**Comment by SeydX** [comment]
@Fofer 

Tried adding a command?

![811D2A7E-AFDB-4E11-BF82-62A38B6FFB9B](https://user-images.githubusercontent.com/34152761/99917870-6fe77380-2d13-11eb-90b8-b550dd72a0c9.gif)

**Comment by Fofer** [comment]
HOLY WOW!  Not sure how I missed that. Works perfectly, obviously. 

This is incredible.  Thank you again!

Is there any way to string multiple commands together, kind of like a macro?  If so, we would be able to string together commands for customized control, and do things like enable a [60 minute sleep timer,](https://github.com/SeydX/homebridge-bravia-tvos/issues/103) via HomeKit :)

**Comment by SeydX** [comment]
Added in v4.1.2

[Example Config](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/example-config.json#L69)
