### ISSUE TITLE
Accessory not showing on Home app

### ISSUE THREAD

**Issue by DanteTheDonkey** [SeydX/homebridge-bravia-tvos#104]
- Installed and configured plug-in with no issues.

- Linked to TV via pin

- Accessory shows up in homebridge. 

Unfortunately, the accessory is not showing in Home app on iphone on 14.3 beta. I really can't see that there is a preference I have missed for it to not show up.

Any idea if this is likely to be an issue with the ios beta?

Thanks

**Comment by SeydX** [comment]
The TV is an external Accessory and must be added separately to HomeKit

Read: https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-add-homebridge-cameras--tvs

**Comment by DanteTheDonkey** [comment]
Now I feel kind of dumb. Thanks!
