### ISSUE TITLE
Volume not working

### ISSUE THREAD

**Issue by fcoura** [SeydX/homebridge-bravia-tvos#105]
Hi SeydX, all good? Thx for all the hard work! It's the absolute best plugin I'm using. Just wanna report that since the 4.0 my volume (from the remote control in the Control Center of my iPhone) is not working... Everything else working fine and the homebridge is sending the commands to the TV ([11/25/2020, 13:51:39] [BraviaOSPlatform] Sony 75: Reducing volume by -1). My TV is a Sony XBR75X855D. Let me know if you need me to send any other info. Thx!

**Comment by SeydX** [comment]
Hey @fcoura 

Have you tried changing the audio output in config?

You can try audio output "others". Maybe this will work

**Comment by fcoura** [comment]
yes! perfect.
