### ISSUE TITLE
Not able to add TV to Home app

### ISSUE THREAD

**Issue by cerahmed** [SeydX/homebridge-bravia-tvos#109]
**History:**

• I have used the previous version of this plugin, been able to add the TV accessory to the Home app.
• The TV accessory was ONLY able to turn off the TV. Could not turn on the TV, change inputs, or do any other operations.
• Deleted the config from Homebridge, and **REMOVED THE ACCESSORY** from the Home app (to be able to add a new accessory later once properly configured).

**Current Issue:**

• Updated to the latest version of the plugin.
• Configured my Bravia TV using the recommended method (Homebridge UI).
• The TV is **successfully configured** and I CAN turn on/off and mute the TV using Homebridge accessory tab.
• The bulb accessory for the speaker shows up in Home, and operates as expected.

• However, **I COULD NOT add the TV accessory manually in the Home app**. As mentioned, I have deleted the previous accessory in order to add the newly-configured one, restarted my iPhone in hopes to remove any cached device information, rebooted my RPi hosting Homebridge, etc. The device just couldn't show up when I go to "Add Accessory -> I Don't Have a Code or Cannot Scan". It seems like something in either the Home app OR Homebridge still holding information about the previous accessory, which in turn denies the new connection to the same home.

Appreciate your help.

**Comment by cerahmed** [comment]
It is worth noting that the following shows up in Homebridge log when restarting the service:

`[11/28/2020, 00:32:53] [Upper Room TV] Upper Room TV: Polling tv state
[11/28/2020, 00:32:53] [Upper Room TV] Upper Room TV: Configured!
[11/28/2020, 00:32:53] Upper Room TV 2B17 is running on port 45143.
[11/28/2020, 00:32:53] Please add [Upper Room TV 2B17] manually in Home app. Setup Code: 934-75-735`

This means that the accessory is indeed not connected to any Home yet.

**Comment by SeydX** [comment]
> It is worth noting that the following shows up in Homebridge log when restarting the service:
> 
> `[11/28/2020, 00:32:53] [Upper Room TV] Upper Room TV: Polling tv state [11/28/2020, 00:32:53] [Upper Room TV] Upper Room TV: Configured! [11/28/2020, 00:32:53] Upper Room TV 2B17 is running on port 45143. [11/28/2020, 00:32:53] Please add [Upper Room TV 2B17] manually in Home app. Setup Code: 934-75-735`
> 
> This means that the accessory is indeed not connected to any Home yet.

This is the normal message suggesting to add the TV separately, tried with another TV name? That you didnt had before

**Comment by cerahmed** [comment]
Superb! Changing the name of the TV did actually help!

Many thanks; really appreciate it.
