### ISSUE TITLE
Home app always displays last "favApps" as active

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#11]
The Home App always displays the last favApps in my config file as active. 

Selecting another app using the "Input" list will update the active app, but as soon as I change the app using the tv remote, the Home App will display the last favApps back.

In my example, "Steam link" is my last favApps in config.json.
![img_0007](https://user-images.githubusercontent.com/4128333/52495341-ad2b5180-2bd0-11e9-962d-bdb8d25162de.PNG)

`   "accessories":[
      {
         "accessory":"BraviaTVOS",
         "name":"TV",
         "interval":10,
         "ipadress":"10.0.1.3",
         "port":80,
         "psk":"sony",
         "extraInputs":false,
         "cecInputs":true,
         "channelInputs":false,
         "favApps":[
            {
               "title":"Netflix",
               "uri":"com.sony.dtv.com.netflix.ninja.com.netflix.ninja.MainActivity"
            },
            {
               "title":"Plex",
               "uri":"com.sony.dtv.com.plexapp.android.com.plexapp.plex.activities.SplashActivity"
            },
            {
               "title":"Molotov TV",
               "uri":"com.sony.dtv.tv.molotov.app.tv.molotov.android.ui.SplashActivity"
            },
            {
               "title":"Prime Video",
               "uri":"com.sony.dtv.com.amazon.amazonvideo.livingroom.com.amazon.ignition.IgnitionActivity"
            },
            {
               "title":"YouTube",
               "uri":"com.sony.dtv.com.google.android.youtube.tv.com.google.android.apps.youtube.tv.activity.ShellActivity"
            },
            {
               "title":"Be tv Go",
               "uri":"com.sony.dtv.be.tv.go.be.voo.voomotion.ui.splashscreen.SplashScreenActivity"
            },
            {
               "title":"VOOmotion",
               "uri":"com.sony.dtv.be.voo.voomotion.be.voo.voomotion.ui.splashscreen.SplashScreenActivity"
            },
            {
               "title":"Steam Link",
               "uri":"com.sony.dtv.com.valvesoftware.steamlink.com.valvesoftware.steamlink.SteamShellActivity"
            }
         ]
      }
   ]
}
`

**Comment by SeydX** [comment]
It is not possible to detect the app states via the API, it always says ‚Illegal State‘ for apps

In v2 i added a new funktion to ‚deactivate‘ the current state (if its an app)

Maybe i will add a statefull favApps to remind the last state of the input source and show them correctly (only if selected via home app, so it will not be possible to detect it if you select manually via remote)

**Comment by lto-tapptic** [comment]
Even with this method from the Bravia API? https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/appcontrol/v1_0/getApplicationStatusList/

**Comment by SeydX** [comment]
Yes even with this method its not possible to get the name or uri or something else from the active app

This method, as u can see, shows only app prameter like curso, text input etc

**Comment by SeydX** [comment]
Added stateful favApps in v2. Should be fixes
