### ISSUE TITLE
homebrideg restart issue

### ISSUE THREAD

**Issue by shannonpasto** [SeydX/homebridge-bravia-tvos#111]
Hi.

Every time I restart homebridge I have to re-add my TV. I can see "Please add [LoungeTV] manually in Home app. Setup Code: 031-45-154" show up each time. Any ideas?

homebridge v1.1.6
homebridge-bravia-tvos v4.1.5

Thanks

**Comment by SeydX** [comment]
If you already added the tv to HomeKit you dont need to add it again. It will always show up because it is an external accessory and Homebridge will print the info everytime on restart

**Comment by shannonpasto** [comment]
What happens is when I restart homebridge the TV in Home stops responding, the channel scroll list disappears and they turn into accessories giving me the option to show as separate tiles. These tiles don't work and I get "On" displayed at the top above the power button (which also doesn't work). If I delete and re-add it works again.
![IMG_1124](https://user-images.githubusercontent.com/7528937/100656803-61e3c380-33a1-11eb-82de-760509f58f30.PNG)

**Comment by SeydX** [comment]
@shannonpasto 

thats normal for external accessories like tv's. Its not a bug. Force close of the home app is enough after restart to show the input list again

Read here: https://github.com/SeydX/homebridge-bravia-tvos/issues/108

**Comment by shannonpasto** [comment]
Strange behaviour though as no other accessory does that but restarting Home fixed it. Thanks.
