### ISSUE TITLE
tv:isdbt as TV source

### ISSUE THREAD

**Issue by kuriburi** [SeydX/homebridge-bravia-tvos#113]
Hello, I live in Japan and the tvsource type for terrestrial broadcast is isdbt. None of the other (dvbt, dvbc, dvbs) types work here. 
Would it be possible to add those (isdbt, isdbc, isdbs) to the dropdown in the UI configuration screen? of course I can always edit the config by hand (which I did) and it works just fine. But as there are a few countries using it, I think it might be worth adding?
https://en.wikipedia.org/wiki/ISDB

cheers, thanks for the great work!

**Comment by SeydX** [comment]
@kuriburi 

Sure, thx!

**Comment by kuriburi** [comment]
Wow, you're quick! thanks for the response.

**Comment by kuriburi** [comment]
Hi, it would also be great to set the type of  tvsource in the initial setup, as right now the channel scanning is done with dvbt by default, and I have to add the channels based on what homebridge-bravia outputs. Thanks!

**Comment by SeydX** [comment]
Added in v4.1.8
