### ISSUE TITLE
Apple home

### ISSUE THREAD

**Issue by Jacobscat** [SeydX/homebridge-bravia-tvos#114]
There’s surely something I’m missing here but in the homebridge hub under the accessories tab I  have my little icon to turn off the tv and on but i can’t get it on the Apple home app only via hitting the add accessory option then selecting can’t scan my tv then appears but it asks for the 8 digit code Is this an issue or how it is 
Supposed to be? or perhaps just a bad initial setup? Hope someone can please help me.

**Comment by lukasmalkmus** [comment]
Interestingly experiencing the same after updating node and some plugins today. I wanted to reconfigure my TV for different reasons. Now I face this issue.

**Comment by lukasmalkmus** [comment]
Multiple restarts resolved it. Maybe need to give HomeKit some time before accepting the code again.

**Comment by Jacobscat** [comment]
That seemed to do it! it’s in my home now Thank you.
