### ISSUE TITLE
Inputs are replaced by individual accessories when HB restarts

### ISSUE THREAD

**Issue by maisun** [SeydX/homebridge-bravia-tvos#117]
Hi,

With the latest version 4.1.8 every time when HomeBridge is restarted, all inputs are gone and replaced by individual accessories named the same as input names. The issue can always be reproduced, and the only solution I found is to remove all cache and re-add the TV. But after a restart the problem comes back again

**Comment by SeydX** [comment]
@maisun 

pls read following issue: 

https://github.com/SeydX/homebridge-bravia-tvos/issues/108

Thats not a bug. Thats how apple handles external accessories. Just force close the apple home app after restarting homebridge. This should fix it

**Comment by maisun** [comment]
Thank you for super fast reply! I can confirm it does the trick and everything works after force restart of Home app.
