### ISSUE TITLE
[Feature Request] Hide inactive entries from "Input" list in Home app

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#12]
Would it be possible to manually (or better, automatically) hide inactive entries from the "Input" menu in the Home app?

As I am using a Home Cinema Amplifier, I'm only using one HDMI port (eARC/ARC). Therefore, I would like the HDMI 1, 2 and 4 to be hidden and only appear if an HDMI cable is plugged to them.

The TV allows to automatically hide the inactive entries from the input menu, so I'm wondering if it would be possible here?!

![img_5db571282fd0-1](https://user-images.githubusercontent.com/4128333/52495819-11024a00-2bd2-11e9-8791-91c8df85bef6.jpeg)

**Comment by SeydX** [comment]
You cen deactivate the input in a 3rd party app like Elgato eve app. Every input has an ‚Active‘ Characteristic, so you can just deactivate it to hide the source

After plugging a ned devide to the tv via hdmi u need to refresh the list manually to detect the device

**Comment by lto-tapptic** [comment]
Ok thanks, I’ll try that then.
