### ISSUE TITLE
Kitchen TV: Can not reach TV

### ISSUE THREAD

**Issue by SergioBraulioCadenaJuarez** [SeydX/homebridge-bravia-tvos#121]
I have two TVs, one of them it is working well but the other one is not working sometime yes and sometime not. Please the error in the logs.

![image](https://user-images.githubusercontent.com/32884256/102296395-db87bf80-3f12-11eb-999f-b2f094658d20.png)

**Comment by SeydX** [comment]
@SergioBraulioCadenaJuarez 

Thats not a ‚bug‘. Some Sony TVs doesnt allow to access the API while in deep sleep. Therefore the plugin shows a warning because it is not reachable.

**Comment by SergioBraulioCadenaJuarez** [comment]
Sorry, thanks a lot for the support. I'll close this one because it is not a issue 😅
