### ISSUE TITLE
TV Sound (Lightbulb) when turning on, sometimes it is 100%

### ISSUE THREAD

**Issue by bjarnet3** [SeydX/homebridge-bravia-tvos#122]
Hello SeydX,,, thanx for the great Sony TV homebridge plugin you have made, I use it everyday.

If I turn the sound off (with 20% volume) and on again "fast", the sound goes back to 20% as expected. But if I turn off all lights (inkl. TV sound lightbulb) and then turn on the TV Sound again sometimes the Volume goes to 100%. 

![620834E0-DA69-489A-9A8D-6EB57A66E1AE_1_105_c](https://user-images.githubusercontent.com/1518155/102787525-80861a80-43a1-11eb-92a6-52185a52558b.jpeg)

![C591C084-E594-4BB6-8981-345A831257E4_1_105_c](https://user-images.githubusercontent.com/1518155/102787561-8e3ba000-43a1-11eb-8e2a-26044ae1d88f.jpeg)

![E172E6D9-3FB0-4D75-AA73-4B5178BE46C8_1_105_c](https://user-images.githubusercontent.com/1518155/102787880-0ace7e80-43a2-11eb-9cb1-f29344c34363.jpeg)

Is there a way to make it like, if the sound is off,, when turning it on it goes to  e.g. 20% ???

Me and my neighbors would really appreciate such a function :-P :-D

Thanx in advance!

**Comment by SeydX** [comment]
Hey @bjarnet3 

it should go back to the previous volume state after turning on the lightbulb. 

I will check this, thx

**Comment by SeydX** [comment]
v5.0.0 is online.

Closing this issue because its related to v4.x. Feel free to open/reopen if the issue still exists on v5.

Please read the [changelog](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/Changelog.md#v500---2021-07-04) on how to migrate to v5
