### ISSUE TITLE
Custom Remote Commands Not Working

### ISSUE THREAD

**Issue by SupImDos** [SeydX/homebridge-bravia-tvos#125]
Thanks very much for your hard work on this plugin!

**_Notes_**:
_Issue 1_:
As you can see below, I would like to add the "Fast Forward" and "Rewind" buttons to my remote, but nothing happens to the remote when I specify this in the config. Am I interpreting something wrong here?

_Issue 1_:
Also, regardless of the input to my TV (e.g. Netflix, Disney+, Youtube), The state of the TV reverts to "On" in the Home app after the next poll of the device state. Is this the current intended behavior?

Thanks!

**_Config_**:

```
        {
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Bravia",
                    "ip": <hidden>,
                    "port": 80,
                    "timeout": 5,
                    "appName": "Bravia",
                    "appUUID": <hidden>,
                    "manufacturer": "Sony",
                    "model": "Bravia",
                    "serialNumber": "KD49X8000H",
                    "apps": [
                        "Netflix",
                        "Stan",
                        "Disney+",
                        "YouTube",
                        "Kayo Sports"
                    ],
                    "commands": [
                        "Home"
                    ],
                    "displayOrder": [
                        "commands",
                        "apps"
                    ],
                    "speaker": {
                        "output": "speaker",
                        "increaseBy": 1,
                        "reduceBy": 1
                    },
                    "remote": [
                        {
                            "command": "Forward",
                            "target": "FAST_FORWARD"
                        },
                        {
                            "command": "Rewind",
                            "target": "REWIND"
                        }
                    ]
                }
            ],
            "platform": "BraviaOSPlatform",
            "debug": true
        }
    ]
}
```

**_Screenshot of the Remote:_** (Note no Fast Foward or Rewind Buttons)
![134292389_229969025400819_3116568136472045074_n](https://user-images.githubusercontent.com/62866982/103282712-959e2180-4a11-11eb-8351-98100791021d.jpg)

**Comment by SeydX** [comment]
@SupImDos 

1) Apple doesnt allow to add/remove buttons to the remote screen. The Plugin only allows to map different codes to the already existing buttons.

2) Its not a problem with the plugin. Sony API doesnt offer app states. If you open an app like Netflix etc. the current state will be ‚Illegal State‘. Due to this reason it will jump to ‚Active‘ on next poll

**Comment by SupImDos** [comment]
@SeydX 
Thank you very much for the reply!

I thought as much, thanks very much for confirming.

So I am unable to add the fast forward/rewind buttons, but does this mean I should be able to rebind the "i" Information button on the remote to execute the "Home" command? I wasn't able to get that working when I last tried, when I'm next home I will attempt it again.

Cheers
