### ISSUE TITLE
Unable to get any Inputs

### ISSUE THREAD

**Issue by simonrb2000** [SeydX/homebridge-bravia-tvos#126]
Hi,

I am struggling to get any inputs onto the app. I have all the applications etc..

This is my config:-
 "platform": "BraviaOSPlatform",
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Sony TV",
                    "ip": "192.168.1.173",
                    "port": 80,
                    "timeout": 5,
                    "appName": "Sony TV",
                    "appUUID": "abd6038c-4d60-4c53-857f-b3cbeb124cad",
                    "inputs": [
                        "extInput:cec",
                        "extInput:hdmi"
                    ],
                    "apps": [
                        "Netflix",
                        "YouTube",
                        "Peloton",
                        "Disney+",
                        "Plex",
                        "Kodi"
                    ],
                    "displayOrder": [
                        "inputs"
                    ],
                    "speaker": {
                        "increaseBy": 1,
                        "reduceBy": 1
                    },
                    "remote": [
                        {
                            "command": "Home",
                            "target": "INFORMATION"
                        }
                    ]
                }
            ]
        }
    ],
    "accessories": []

Many Thanks

Simon

**Comment by SeydX** [comment]
Screenshot from tv accessory? Output from log?
