### ISSUE TITLE
Unable to add tv via accessory

### ISSUE THREAD

**Issue by tanjello** [SeydX/homebridge-bravia-tvos#128]
I had to remove the tv from homekit and when I went to add it back in the Home app, it does not find it from "add accessory" anymore. 

I've tried:
-Reboot TV
-Factory reset tv
-Reboot homebridge + box
-Uninstall plugin and reinstall
-Completely delete home and rebuild

HELP!
Thanks

**Comment by SeydX** [comment]
@tanjello 

just change the name and re add again

**Comment by tanjello** [comment]
Yup that fixed it. Cant believe I didnt think about that. 

Thanks
