### ISSUE TITLE
New update not working Node error

### ISSUE THREAD

**Issue by ramonvanbiljouw** [SeydX/homebridge-bravia-tvos#13]
After installation now I get the node version error like previously reported; 

Plugin /homebridge/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v10.15.1. You may need to upgrade your installation of Node.

I run homebridge Version 0.4.46.
Hopefully you can help me out. Thanks, Ramon

**Comment by ramonvanbiljouw** [comment]
Reading is a form. of art.... I fixed it.

**Comment by SeydX** [comment]
What was the problem?

**Comment by ramonvanbiljouw** [comment]
You moved it from an accessory item to a platform item...
