### ISSUE TITLE
Delayed responses, errors in the logs and non-functioning remote 

### ISSUE THREAD

**Issue by Soldiiier** [SeydX/homebridge-bravia-tvos#130]
After a few good days of using the plugin without issue, I am now seeing many errors in the HB terminal view.

Changing volume via remote is no longer operable, turning off the tv I can witness a huge delay in the physical switch off.
I am not having any of these delay issues with the other Sony plugin.

I have removed the plugin, and external device, and re-added, however the experience is the same

**Comment by Soldiiier** [comment]
![IMG_0274](https://user-images.githubusercontent.com/16224280/106529845-4df24480-653f-11eb-88df-5f03f824a737.jpeg)

**Comment by Soldiiier** [comment]
changing/keeping the original default timeout of 5 seconds hasn't change anything.

**Comment by idominiki** [comment]
Have the same problem, also mentioned in issue #120 

Change from PSK to PIN doesn't help

**Comment by SeydX** [comment]
Hey guys can u try v4.1.10 pls
