### ISSUE TITLE
HomeKit not showing

### ISSUE THREAD

**Issue by Captainkyle420** [SeydX/homebridge-bravia-tvos#131]
Doesn’t show up in HomeKit app ios14. But shows up and functions in homebidge GUI 
![98EC274F-4A2B-4430-93FF-65BFB76FDDEB](https://user-images.githubusercontent.com/15304010/107131592-0e0bc400-6895-11eb-9780-9357a52c5cc7.jpeg)
![2969956E-B752-4DCD-94DB-EB0C092E108A](https://user-images.githubusercontent.com/15304010/107131595-119f4b00-6895-11eb-98eb-c8ec3b280314.jpeg)

**Comment by ondraradon** [comment]
Hi, I have the same problem

**Comment by ohadme** [comment]
Hi 
I have the same problem,
any solution?

**Comment by SeydX** [comment]
Hey all,

u need to add it as a separate accessory, see here

https://github.com/SeydX/homebridge-bravia-tvos/issues/108

If the problem persists, try changing the tv name in your config and try again

**Comment by ohadme** [comment]
WOW 
works amazing :) Thank you
