### ISSUE TITLE
slow to respond errors 

### ISSUE THREAD

**Issue by skir0cket** [SeydX/homebridge-bravia-tvos#132]
I keep getting this error and also timeout errors when operating the plugin to switch the inputs or turn off

"This plugin slows down Homebridge. The write handler for the characteristic 'Active' on the accessory 'Tv C344' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."

**Comment by SeydX** [comment]
@skir0cket 

should be fixed with v4.1.10

**Comment by Austin519** [comment]
I was having the same issue and it was resolved by switching from token to psk authentication method.  I believe the token method is the issue.
