### ISSUE TITLE
Feature Request: define a dedicated port to run your application

### ISSUE THREAD

**Issue by iGodPhil** [SeydX/homebridge-bravia-tvos#135]
Hi at the moment I am unable to use your plugin because your application is switching the port at every restart of my homebridge instance. The reason is my ufw firewall which blocks the traffic after a restart because the port has changed. 
It would be nice to configure a dedicated port where your plugin is running.Is it possible to include this function?

**Comment by SeydX** [comment]
Sure

**Comment by iGodPhil** [comment]
That would be nice.

**Comment by SeydX** [comment]
Hey, apparently I didn't read it right. The plugin itself cannot change the port of your Homebridge instance. That is managed by Homebridge itself.
