### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by RossiHovitez** [SeydX/homebridge-bravia-tvos#136]
found 0 vulnerabilities
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
hoobs@hoobs:/home/hoobs/.hoobs/etc $ npm fund
@hoobs/hoobs@3.3.5
+-- https://github.com/sponsors/feross
|   `-- safe-buffer@5.2.1
`-- https://github.com/sponsors/epoberezkin
    `-- ajv@6.12.6

**Comment by SeydX** [comment]
????

**Comment by RossiHovitez** [comment]
The install just fails.  Says 2 funds missing.

**Comment by RossiHovitez** [comment]
Both using code or the ui
