### ISSUE TITLE
Change volume relative to current volume

### ISSUE THREAD

**Issue by thokon** [SeydX/homebridge-bravia-tvos#137]
Great plugin - many thanks, using it heavily at the moment. 

The only thing I'm missing would be a command that I could trigger, that increases the volume of the speaker always by a fixed value. E.g. so that I could trigger "Hey Siri, increase TV volume", which would cause the TV's volume to be increased by "5".

I've seen in your documentation that there's an option "speaker.increaseBy". Apparently this function is only picked up by AppleRemote (which I don't use).

Any recommendations, how I could achieve this?

Cheers!!!

**Comment by SeydX** [comment]
Do you have tried to set speaker "accType" to "lightbulb" ?

On my test environment it works with following command: "Hey Siri, increase <Speaker Lightbulb Name> by 20%"
