### ISSUE TITLE
Can anyone please explain how I can use the Apple Remote fuction?

### ISSUE THREAD

**Issue by azosnu** [SeydX/homebridge-bravia-tvos#138]
How does this feature actually work?

I set the command of "TV Off" and set the remote target to "Settings" How can I use this action?

I open the TV Remote from control center and I don't see any Settings icon. 

Thanks.

**Comment by SeydX** [comment]
The "Settings" button is NOT in the Apple Remote screen.

Its in HomeKit under your TV Accessory

![IMG_1162](https://user-images.githubusercontent.com/34152761/124136464-1a333080-da85-11eb-868b-b96e06c9e0bb.PNG)
