### ISSUE TITLE
Not Showing In Homekit

### ISSUE THREAD

**Issue by JGP7229** [SeydX/homebridge-bravia-tvos#139]
completed installation, can turn on and off from homebridge but can not get the TV to show in the HomeKit app. Any suggestions? I've restarted home bridge numerous times with no luck.

Thank you

**Comment by QiuYueBaiJXW** [comment]
same too,need your help

**Comment by seydx** [comment]
> same too,need your help

The TV is registered as "External Accessory", it has to be added manually in Home app once. Just tap on "+" -> "Add new Device" -> "No code" and you should see your TV. The code is the same as the one your Homebridge uses.

**Comment by bxlouis** [comment]
@seydx I get the same issue with iOS 15.1.1.
The TV accessory shows up in Homebridge UI but I cannot add it to the Home app.
The accessory does not show up there and typing the Homebridge code does not work either as it is already registered.

I removed the homebridge hub and added it again, cleared the cache... The issue remains.

Any idea?

**Comment by QiuYueBaiJXW** [comment]
Try to change your tv name in Bravia tvOS 
It works fine when I changed the name, you can have a try.

**Comment by bxlouis** [comment]
> Try to change your tv name in Bravia tvOS
> It works fine when I changed the name, you can have a try.

@QiuYueBaiJXW it did the trick. Thanks a lot!
