### ISSUE TITLE
Feature request: homekit support for older sony bravia models that have full ip control

### ISSUE THREAD

**Issue by ronvandeven** [SeydX/homebridge-bravia-tvos#14]
First of all very good plugin and I’m very happy with it. Installation and config was easy, I was using an other plugin first could not get it to work, this one was painless.

I have 2 sony bravias at home, one that has android OS w805c and one that has what i think is a sony OS w805a.
I was using roomie remote before which was later renamed to simple control. Which had full ip control on both TV’s, bidirectional traffic, including wake on lan, but is not part of the homekit ecosystem this way. I was hoping for extra support to get this TV into homekit as well via homebridge.

**Comment by ronvandeven** [comment]
@SeydX thank you for looking into this. Because nowadays the economical rest value of an old 55 inch 1080p Bravia is quite low I would like to keep it until it breaks, because it is still a great screen.

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
