### ISSUE TITLE
Stop pooling if WOL is activated

### ISSUE THREAD

**Issue by lukasmalkmus** [SeydX/homebridge-bravia-tvos#140]
My logs are getting spammed with these:

```
[5/7/2021, 5:05:15 PM] [BraviaTVOS] TV: Can not reach TV!
```

The reason is simple: I have a pretty old Bravia model (~8yrs). While all standby and energy settings are configured correctly, the http server of the TV only seems to be available till 15 minutes after the TV was turned off. After that, logs get spammed till it's turned on again. Also, turning on only works by WOL, because the https server isn't available.

It would be awesome to have an option, which does not pool the TV state by using http. Or at least fall back to something else or fail silently. Maybe we can figure something out?

**Comment by SeydX** [comment]
Fixed in current version. 

``TV: Can not reach TV!`` is only visible when debug is enabled now

**Comment by lukasmalkmus** [comment]
Nice, thanks!
