### ISSUE TITLE
Soundbar does not get activated when started via HomeKit.

### ISSUE THREAD

**Issue by lukasmalkmus** [SeydX/homebridge-bravia-tvos#141]
I have a Sonos Beam soundbar connected to my Sony Bravia via HMDI ARC. When the TV is cold started (having been turned of for more than 15 minutes with the http server not being available) using HomeKit (WOL it is for me!), I get not sound. The TV shows a prompt saying something like "Soundsystem connected", but the Soundbar does not pick up the TV as sound source. Interestingly, with the same parameters (TV being turned off for more than 15 mins), it works when using the default hardware remote.

**Comment by SeydX** [comment]
v5.0.0 is online.

Closing this issue because its related to v4.x. Feel free to open/reopen if the issue still exists on v5.

Please read the [changelog](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/Changelog.md#v500---2021-07-04) on how to migrate to v5
