### ISSUE TITLE
Speaker accessory type problem

### ISSUE THREAD

**Issue by gferreroferri** [SeydX/homebridge-bravia-tvos#142]
When I configure my tv speaker as accessory type “Speaker” I get an incompatible accessory in Home app. It seems to work only as a “Lightbulb” type. Is this normal?

**Comment by SeydX** [comment]
Yea thats intended. "Speaker" type is not supported in Apple Home and only visible in third party apps like EVE etc.

in the next major release (v5), this type will be removed
