### ISSUE TITLE
Rebinding remote control functions is not working

### ISSUE THREAD

**Issue by BlackyHole99** [SeydX/homebridge-bravia-tvos#145]
I have a Sony A8F running with the latest android update. Connection using the homebridge plugin is running fine so far, but I‘m not able to rebind the ios remote control functions.

It doesn‘t matter which command I try or which target I choose.
For example, mapping ActionMenu to Information doesn‘t change anything. After restarting the homebridge the information button is still sending the information command. 
Also mapping something similiar to the settings target key to test if it‘s an issue with the control center remote, since this function is (as far as I know) only available in the home app, is unfortunately not working.

Is there a missunderstanding from my side?
My config file looks like this:

```
        {
            "platform": "BraviaOSPlatform",
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Sony TV",
                    "ip": "192.168.178.7",
                    "port": 80,
                    "timeout": 5,
                    "psk": "XXXXXX",
                    "inputs": [
                        "[extInput:hdmi] HDMI 1",
                        "[extInput:hdmi] HDMI 2",
                        "[extInput:hdmi] HDMI 3/ARC",
                        "[extInput:hdmi] HDMI 4"
                    ],
                    "speaker": {
                        "increaseBy": 1,
                        "reduceBy": 1
                    },
                    "remote": [
                        {
                            "command": "ActionMenu",
                            "target": "INFORMATION"
                        }
                    ]
                }
            ],
            "debug": false
        }
```

I also checked the debug output, but without any hints, what could be wrong.

Some more information about my environment:
I‘m running homebridge in a docker container with no avahi on a raspberry pi 4 with 64-bit.

Thanks in advance and also thanks for your great work!

**Comment by SeydX** [comment]
Hey @BlackyHole99 

v5.0.0 is online.

Releasing this issue because its related to v4.x. Feel free to open/reopen if the issue still exists on v5.

Please read the [changelog](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/Changelog.md#v500---2021-07-04) on how to migrate to v5
