### ISSUE TITLE
Config is not saved, if changed over the HB-Config-Gui

### ISSUE THREAD

**Issue by thokon** [SeydX/homebridge-bravia-tvos#146]
Hey there, currently using following setup:

Homebridge Version v1.3.4
Homebridge Bravia Tvos  Version v5.0.1
Node.js Version v14.17.3
NPM Version v6.14.13

I can add new TVs using the wizzard, unfortunately, I can not add applications etc. using the GUI (I can select the in the GUI, after restarting HB these changes are not reflected in the config). Also if I open up the config after restarting, the previously added applications and settings are lost.

Here's my current config:

`{
    "name": "BraviaTVOS",
    "platform": "BraviaOSPlatform",
    "debug": true,
    "warn": true,
    "error": true,
    "extendedError": true,
    "tvs": [
        {
            "active": true,
            "name": "Fernseher",
            "ip": "192.168.0.7",
            "port": 80,
            "manufacturer": "Sony",
            "model": "Bravia",
            "serialNumber": "00000000",
            "wol": false,
            "refreshInputs": false,
            "polling": 10,
            "sheduledRefresh": 12,
            "inputs": [],
            "apps": [],
            "channels": [],
            "commands": [],
            "macros": [],
            "remote": [],
            "displayOrder": [
                "inputs",
                "apps",
                "channels",
                "commands",
                "macros"
            ],
            "speaker": {
                "active": true,
                "output": "speaker",
                "increaseBy": 1,
                "reduceBy": 1,
                "accType": "lightbulb"
            },
            "psk": "1234"
        }
    ]
}`

**Comment by SeydX** [comment]
Hey, after adding a new tv or input you need to „save“ it with clicking on the „save“ button at the bottom

**Comment by thokon** [comment]
Hey, that's what I did:

![BAA097C8-441C-478A-BD4C-7B60D6CBE061_1_105_c](https://user-images.githubusercontent.com/82800325/125316213-31e99f00-e338-11eb-9178-f8304380f3d4.jpeg)

**Comment by thokon** [comment]
I downgraded to 4.12.1 on the same instance, and the config could be saved again. After that i reupgraded to 5.0.1 and the config is not persisted anymore. 

Maybe something that might relate to that behaviour. Occasionally I get the error message r.apps is undefined; but can not really reproduce that message.

**Comment by SeydX** [comment]
v5.0.2 is online

**Comment by SeydX** [comment]
should be fixed with v5.0.3
