### ISSUE TITLE
Authorization  

### ISSUE THREAD

**Issue by GRClark** [SeydX/homebridge-bravia-tvos#147]
Two questions: every time I reboot my raspberry pi I get a prompt on the Bravia screen with the authorization number - where should I be going in homebridge ui to enter this number and is there a way to authorize only once and not be prompted each time?

**Comment by SeydX** [comment]
Can u post your config.json pls

**Comment by GRClark** [comment]
{
    “bridge”: {
        “name”: “Homebridge 0753”,
        “username”: “0E:53:4B:0B:07:53”,
        “port”: 52302,
        “pin”: “031-45-154”,
        “advertiser”: “ciao”
    },
    “accessories”: [
        {
            “name”: “Dummy”,
            “stateful”: true,
            “reverse”: false,
            “time”: 1000,
            “accessory”: “DummySwitch”
        },
        {
            “name”: “Bypass”,
            “stateful”: true,
            “reverse”: false,
            “time”: 1000,
            “accessory”: “DummySwitch”
        },
        {
            “name”: “Reset”,
            “stateful”: false,
            “reverse”: false,
            “time”: 1000,
            “accessory”: “DummySwitch”
        },
        {
            “accessory”: “PowerlossPushoverNotifier”,
            “name”: “PowerlossPushoverNotifier”,
            “token”: “a5oytc963cuifw3w37167zhgmg2x27”,
            “user”: “uxmsj5a28waic3azbdtqi1cp655cth”
        }
    ],
    “platforms”: [
        {
            “addAllActivitiesToSkippedIfSameStateActivitiesList”: true,
            “publishGeneralMuteSwitch”: true,
            “mainActivity”: “Watch TV”,
            “publishSwitchActivitiesAsIndividualAccessories”: true,
            “publishDevicesAsIndividualAccessories”: true,
            “hubIP”: “10.0.0.136”,
            “platform”: “HarmonyHubWebSocket”,
            “publishHomeControlsAsIndividualAccessories”: true,
            “playPauseBehavior”: true,
            “switchAccessories”: true,
            “numberOfCommandsSentForVolumeControl”: 5,
            “publishSequencesAsIndividualAccessories”: true,
            “showCommandsAtStartup”: true,
            “name”: “Harmony Hub”,
            “publishAllTVAsExternalAccessory”: false,
            “TVAccessory”: true,
            “plugin_map”: {
                “plugin_name”: “homebridge-harmony”
            },
            “cleanCache”: false
        },
        {
            “platform”: “Pushover”,
            “name”: “Messages”,
            “pushover”: {
                “user”: “XXXX”,
                “token”: “XXXX”
            },
            “messages”: [
                {
                    “name”: “Active”,
                    “message”: “System Active”
                },
                {
                    “name”: “Disabled”,
                    “message”: “System Disabled”
                },
                {
                    “name”: “Privacy”,
                    “message”: “Privacy Enabled”
                },
                {
                    “name”: “Alert”,
                    “message”: “Attention: System Alert”,
                    “priority”: “high”
                },
                {
                    “name”: “Alarm”,
                    “message”: “Attention: Security Alert”,
                    “priority”: “high”
                }
            ]
        },
        {
            “name”: “SmartThings-v2”,
            “app_url”: “https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/“,
            “app_id”: “32d973c7-9ce8-44ee-9303-6751a50f39cd”,
            “access_token”: “XXXX”,
            “communityUserName”: “GRClark”,
            “direct_ip”: “10.0.0.170”,
            “direct_port”: 8000,
            “temperature_unit”: “F”,
            “validateTokenId”: true,
            “logConfig”: {
                “debug”: false,
                “showChanges”: true,
                “hideTimestamp”: false,
                “hideNamePrefix”: false,
                “file”: {
                    “enabled”: true,
                    “level”: “pink”
                }
            },
            “platform”: “SmartThings-v2”
        },
        {
            “name”: “Config”,
            “port”: 8222,
            “auth”: “none”,
            “theme”: “deep-purple”,
            “tempUnits”: “f”,
            “lang”: “en”,
            “sessionTimeout”: 43200,
            “platform”: “config”
        },
        {
            “platform”: “AlexaPlayer”,
            “amazonDomain”: “amazon.com”,
            “auth”: {
                “proxy”: {
                    “clientHost”: “10.0.0.170”,
                    “port”: 25392
                }
            },
            “screensAsTelevisions”: true
        },
        {
            “name”: “Google Smart Home”,
            “token”: “XXXX.eyJpZCI6ImdpdGh1Ynw1MTE4MDU5IiwiaWF0IjoxNjE4NDI5NzIwfQ.bqH3xWm5KYBhGl4ayqiJn4Xl19kyG5cWsIAtcsAIPgI”,
            “notice”: “Keep your token a secret!”,
            “forceFahrenheit”: true,
            “platform”: “google-smarthome”
        },
        {
            “name”: “BraviaTVOS”,
            “tvs”: [
                {
                    “name”: “BRAVIA”,
                    “ip”: “10.0.0.155”,
                    “port”: 80,
                    “timeout”: 5,
                    “appName”: “BRAVIATV”,
                    “appUUID”: “a1e79e4f-8f95-4602-b928-3040a4844229”,
                    “model”: “x900h”,
                    “refreshInputs”: false,
                    “speaker”: {
                        “output”: “speaker”,
                        “increaseBy”: 1,
                        “reduceBy”: 1
                    }
                }
            ],
            “platform”: “BraviaOSPlatform”
        },
        {
            “tvs”: [
                {
                    “name”: “ALIEN”,
                    “ip”: “10.0.0.155”,
                    “mac”: “14:3F:A6:4D:77:A4”,
                    “externalaccessory”: true,
                    “soundoutput”: “speaker”,
                    “applications”: [
                        {
                            “title”: “TiviMate”
                        },
                        {
                            “title”: “Cinema”
                        },
                        {
                            “title”: “Cyberflix”
                        },
                        {
                            “title”: “Netflix”
                        },
                        {
                            “title”: “Prime”
                        },
                        {
                            “title”: “YouTube”
                        }
                    ]
                }
            ],
            “platform”: “BraviaPlatform”
        }
    ]
}

**Comment by SeydX** [comment]
The  authorization number (PIN) must be entered during configuring the TV like here: https://github.com/SeydX/homebridge-bravia-tvos#configuration-config-ui-x

Reconfiguring the TV with Config UI X should fix it
