### ISSUE TITLE
Error while updating 

### ISSUE THREAD

**Issue by GRClark** [SeydX/homebridge-bravia-tvos#148]
Getting the following message when trying to update saying NoseJS isn’t new enough version and have even gone ahead and updated to latest stable version of 12.22.1.  Not sure if I should proceed with update or not and what implications might be if I do. 

![D7DB6571-A501-4923-A1AE-829608477A9E](https://user-images.githubusercontent.com/5118059/125480029-0affab2d-9329-4949-a102-f1a8c70739df.jpeg)

**Comment by SeydX** [comment]
its not an error, its just a "warning"

u can ignore it
