### ISSUE TITLE
considering TV Volume accessory as a lightbulb issue

### ISSUE THREAD

**Issue by mrsbaaa** [SeydX/homebridge-bravia-tvos#151]
Hello.. 

What's a greet plug.... thank you..

One issue when want to control volume from Home app its only show (switch or lightbulb)..

lightbulb works great but when I ask siri to switch room light it will mute TV too!

is there any other accessory  option you can add? maybe fan or other type that support percentage control?

**Comment by mrsbaaa** [comment]
Gents Any comment?

**Comment by SeydX** [comment]
Added in v5.0.5
