### ISSUE TITLE
Issue Setting up Account With Pin Manually

### ISSUE THREAD

**Issue by hawartens** [SeydX/homebridge-bravia-tvos#155]
Was having an issue setting up homebridge-bravia-tvos. Took a look through the code and think I figured out the issue. The instructions indicate that we should download the bravia tool:
`sudo npm i -g @seydx/bravia@latest`

However, that tool defines the function `genUUID` that does not depend on the `appName` at all:
```
genUUID () {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
      var r = Math.random() * 16 | 0; var v = c == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }
  ```

I modified this function to do the same as the one that comes packaged with `homebridge-bravia-tvos` (does a sha1 of the appName). Now I am able to use this plugin properly. I believe that the `genUUID()` in `@seydx/bravia@latest` needs to be in sync with the `genUUID()` in `homebridge-bravia-tvos`. Thanks!

**Comment by SeydX** [comment]
Fixed
