### ISSUE TITLE
Inputs don’t work with iOS 15

### ISSUE THREAD

**Issue by lukasmalkmus** [SeydX/homebridge-bravia-tvos#158]
The Home App on iOS 15 Beta doesn't show the configured TV inputs anymore. It works fine with iOS 14.7.x. Is that a downgrade in functionality on HomeKit side or are there some TV accessory changes this plugin needs to implement?

**Comment by SeydX** [comment]
For me, its working as expected with the latest iOS 15

**Comment by lukasmalkmus** [comment]
Hm. I correctly configured the inputs and can also see them in the Homebridge Plugin Config UI. But since the first Beta release, I just see this:

![1](https://user-images.githubusercontent.com/9931588/133980379-9ea065ab-2d7b-40d5-ac30-7204043c38ba.jpeg)
