### ISSUE TITLE
Refreshing TV cache does not update [TV Name].json

### ISSUE THREAD

**Issue by blamlo** [SeydX/homebridge-bravia-tvos#159]
I have been unable to build a full cache of my TV inputs. During initial scan, the UI hangs during the scanning of channels (I only have 13 channels). Sometimes it indicates the scan is complete, other times it times out. The result is either a blank or truncated/incomplete cache file. Refreshing the cache does not result in a modified cache file. I've replicated this in 5.0.0, 5.0.1, and 5.0.2 beta. The TV is XBR-65X900F

**Comment by SeydX** [comment]
Can u post the log from the configuration of the tv pls

**Comment by SeydX** [comment]
can u try v5.0.3 pls

**Comment by SeydX** [comment]
Fixed in v5.0.5
