### ISSUE TITLE
Remote buttons won’t appear on iphone

### ISSUE THREAD

**Issue by talrhv** [SeydX/homebridge-bravia-tvos#164]
Hi,

I have a Bravia XE8096 and the remote that I see on my iPhone is just a simple Apple TV remote. I don’t see a remote with all the buttons that I created on the plug-in. 

iOS version 14.5
Latest plugin version and latest homebridge version. 

Thanks

**Comment by talrhv** [comment]
But where should I see the remote I created?

This is what I see in the home app

**Comment by SeydX** [comment]
![F43C20E1-FF4C-4901-8A48-3AFCFE1D5CD9](https://user-images.githubusercontent.com/34152761/134782785-453a45fc-649d-4e6c-b903-977ccb576704.png)

**Comment by talrhv** [comment]
![3E6FCE11-9AF3-4B28-B832-24E0C290456E](https://user-images.githubusercontent.com/34038314/134782903-fafd54ef-bd1f-4d08-aa2a-4b03f975c069.png)
![B8085552-DB0C-4E26-A346-9D6B3DC6373A](https://user-images.githubusercontent.com/34038314/134782904-4c07371d-6901-4bbf-92ad-15dfdbecd55f.png)

**Comment by SeydX** [comment]
Yeah thats intended, the lightbulb (speaker) can be separated as follow


https://user-images.githubusercontent.com/34152761/134783117-d3849cc8-9cdc-4e9a-89eb-2d3b21c366cd.MP4


And the „remote“ field in the config is for the apple tv remote to remap the buttons, if the default one not working for you, you can put other commands into the config
