### ISSUE TITLE
Bug when selecting “Enter” on remote

### ISSUE THREAD

**Issue by talrhv** [SeydX/homebridge-bravia-tvos#165]
Hi,

when I try to set up the remote on the plug-in settings when I set the command “select” and select the value “enter” it is changing to “Num12” after saving.

thanks
![AC1B7C1B-CC9E-4EA1-804A-2AF4A0C08B65](https://user-images.githubusercontent.com/34038314/135120916-3b351abb-8569-438f-bb5b-cf43371645fd.png)
![670FEEAE-9B0F-4C26-8D63-6F99A9D8465A](https://user-images.githubusercontent.com/34038314/135120928-1ca3de8c-f0e2-4f13-817a-a283cf7dc1a4.png)

**Comment by SeydX** [comment]
Hey, can u test v5.0.7-beta.2 pls

``sudo npm i -g homebridge-bravia-tvos@beta``
