### ISSUE TITLE
Apple TV Not Being Cached as CEC Input, Rather as an Application

### ISSUE THREAD

**Issue by iSteve-O** [SeydX/homebridge-bravia-tvos#166]
I've been trying to add my AppleTV connected to "HDMI 3/ARC" as both an "HDMI" input and a "CEC" input, but the CEC is being cached by the plugin as an application instead of an input. I figured this out by checking the cached TV file the dev pointed me to that is named after the device (attached).

I was able to make it appear by adding the CEC input as an app, but it doesn't function properly if you try to switch to it. It does display properly when the tv auto-switches to that input,  you just can't switch to it manually in Home.app. 

I also have a PS4 configured as I want the ATV, to show as both HDMI & CEC inputs, and that one is working without issue, so this makes me believe it is related to the way the plugin picked up the AppleTV on CEC. 

I'm sorry to say I can't confirm if this is related to tvOS 15 messing with CEC because I didn't try to add this CEC input until after updating to tvOS 15 on the ATV.

I tried changing the name of the Apple TV, swapping the inputs of the PS4 & ATV (HDMI 3/4) and many different configs.

I have attached my config showing that the ATV should show up in the input list as both "Apple TV CEC" as an application and "Apple TV CECi" as an input, but it only shows the application in the attached screenshot and not the configured input.

Thanks for your great work on the plugin! It really works great!

[Bravia TV.json](https://github.com/SeydX/homebridge-bravia-tvos/files/7264604/Bravia.TV.json.txt)
[config.json](https://github.com/SeydX/homebridge-bravia-tvos/files/7264610/config-stripped.json.txt)
[Home.app Input Screenshot](https://user-images.githubusercontent.com/10133108/135574259-a7196820-8a4a-4f10-b1ef-250b4542aa16.jpeg)

**Comment by SeydX** [comment]
Thanks, the hint was really helpful! Because of this, i could fix several major issues! 

New Beta version is out, u can test it with:

``sudo npm i -g homebridge-bravia-tvos@beta``

**Comment by iSteve-O** [comment]
Beautiful work, my friend! All inputs now fully functional!

I really appreciate your super fast response and great work on the plugin!

The beta seems to be a treat!
