### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by peligon1** [SeydX/homebridge-bravia-tvos#167]
Hi, first of all great plugin thank you for all your efforts and time. Question, I have the Sony Z9D 65" it pairs very well with the plugin but my volume appears as "Brightness" is there a way to correct this?? Thank you in advance

**Comment by SeydX** [comment]
Sure, u can change it to switch or fan (speaker not supported)

https://github.com/SeydX/homebridge-bravia-tvos/blob/1f609cd2a6e7f799d6ba907246bac17284fec036/example-config.json#L221
