### ISSUE TITLE
Status not reported 

### ISSUE THREAD

**Issue by Sammy990** [SeydX/homebridge-bravia-tvos#17]
After replacing with V2, the status of the device isn’t updated anymore. Keeps showing offline when turned on via regular remote. 

Turning on, off and switching  channels works as expected.

Any idea how to fix that?

**Comment by SeydX** [comment]
With device you mean the tv? Or input? Can you post your log and config.json pls

**Comment by Sammy990** [comment]
I mean the tv, will post the config later today. 
By the way...I have the V3 plugin still running as well on the same instance. Both, v1.1 and v3 were running well. May there be the new v2 and old v3 can not run together?

**Comment by paqpaqpaq** [comment]
I have the same issue.
It seems to work the first time after reboot, and then it just keeps stating OFF, whilst TV is on.
Same goes for updating the chosen function from the TV remote.

**Comment by SeydX** [comment]
I will check this later, thx for feedback

**Comment by paqpaqpaq** [comment]
Hi @SeydX 
Any luck on this?

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
