### ISSUE TITLE
Q: iOS15.2 accessory not discovered

### ISSUE THREAD

**Issue by ursusHU** [seydx/homebridge-bravia-tvos#178]
Today I have installed iOS 15.2, and I also tried to upgrade the plugin from v4.1.12 to the latest one. Unfortunately there was some problem with the inputs, so I tried also to remove the TV accessory from the Home app, and now I ended up, that I can't add the accessory to Home anymore, the accessory is visible in Homebridge, however it can't be discovered it. 
This might be related to the iOS version, or something else...
Anyone else could confirm that it still works with 15.2? 
Thanks!

**Comment by seydx** [comment]
Just change the tv name in your config.json and restart homebridge

**Comment by ursusHU** [comment]
Thank you for your fast response!
