### ISSUE TITLE
Volume control not working 

### ISSUE THREAD

**Issue by Sammy990** [SeydX/homebridge-bravia-tvos#19]
Hi, since iOS Beta 12.2 the volume control doesn‘t work anymore in the AppleTV interface. 

Can you have a look if that is a issue with the beta or maybe they changed something so you need to update your code?

Thanks

**Comment by SeydX** [comment]
Tried with beta 3? I dont have any issues with state, can u post your log pls

**Comment by SeydX** [comment]
I have the same issue, will open a issue on hap-nodejs

Think the new beta hab changed something here

**Comment by SeydX** [comment]
https://github.com/KhaosT/HAP-NodeJS/issues/645

**Comment by SeydX** [comment]
Seems to be fixed in beta4 !
