### ISSUE TITLE
Apple remote buttons do not work with iOS 12.2 beta3

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#20]
Hi,

The latest beta came with a redesigned Apple native remote (cf. screenshot).
The three buttons at the bottom do not work as expected (Play/Pause, Back and "i").

![img_0009](https://user-images.githubusercontent.com/4128333/53161566-84d92500-35ca-11e9-912c-ea322a1597df.PNG)

**Comment by SeydX** [comment]
Thx for report, i have the same problem, i will check this

**Comment by bxlouis** [comment]
Back button seems to work back with iOS 12.2 beta 4 but not Play/pause and « i ».

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
