### ISSUE TITLE
No input with iOS 12.2 beta3

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#21]
The input menu is now empty with the iOS 12.2 beta3 release.
It is working fine with 12.2 beta2 and nothing changed in my config file.
I can also see the input load correctly in the homebridge logs.

![screenshot 2019-02-21 at 11 23 24](https://user-images.githubusercontent.com/4128333/53161912-324c3880-35cb-11e9-98d9-b4eaeaf9dd04.png)

![img_0010](https://user-images.githubusercontent.com/4128333/53161759-e1d4db00-35ca-11e9-9dfc-69f7307b23a0.PNG)

**Comment by SeydX** [comment]
It seems the plugin have issues with syncing the data

tried to restart or reconfigure?

**Comment by bxlouis** [comment]
I tried to restart and always get the same behaviour. I realised that all my inputs are now displayed as individual devices in the Home app (cf. screenshot).

Not sure how I should reconfigure the plugin since I did not modify my configuration since beta2. 
Here is my config.json file:

`{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:4E:E4:DE:36",
      "port":51826,
      "pin":"033-45-156"
   },
   "description":"Configuration file for (e)xtended Domoticz platform.",
   "platforms":[
      {
         "platform":"eDomoticz",
         "name":"eDomoticz",
         "server":"127.0.0.1",
         "port":"8080",
         "ssl":0,
         "roomid":2,
         "mqttenable":1,
         "mqttserver":"127.0.0.1",
         "mqttport":"1883",
         "mqttauth":0,
         "mqttuser":"",
         "mqttpass":""
      },
      {
         "platform":"homebridge-plex-sensors.Plex",
         "sensors":[
            {
               "name":"Plex Playing",
               "players": ["BRAVIA 4K UR1"]
            }
         ]
      },
          {
         "platform": "BraviaOSPlatform",
         "tvs": {
                        "1": {
                "name":"TV",
                "interval":10,
                "ipadress":"10.0.1.3",
                "port":80,
                "psk":"sony",
                "extraInputs":false,
                "cecInputs":true,
                "channelInputs":false,
                "favApps":[
            {
               "title":"Netflix",
               "uri":"com.sony.dtv.com.netflix.ninja.com.netflix.ninja.MainActi$
            },
            {
               "title":"Plex",
               "uri":"com.sony.dtv.com.plexapp.android.com.plexapp.plex.activit$
            },
            {
               "title":"Molotov TV",
               "uri":"com.sony.dtv.tv.molotov.app.tv.molotov.android.ui.SplashA$
            },
            {
               "title":"Prime Video",
               "uri":"com.sony.dtv.com.amazon.amazonvideo.livingroom.com.amazon$
            },
            {
               "title":"YouTube",
               "uri":"com.sony.dtv.com.google.android.youtube.tv.com.google.and$
            },
            {
               "title":"Be tv Go",
               "uri":"com.sony.dtv.be.tv.go.be.voo.voomotion.ui.splashscreen.Sp$
            },
            {
               "title":"VOOmotion",
               "uri":"com.sony.dtv.be.voo.voomotion.be.voo.voomotion.ui.splashs$
            },
            {
               "title":"Steam Link",
               "uri":"com.sony.dtv.com.valvesoftware.steamlink.com.valvesoftwar$
            }
                ]
          }
        }
      }
   ],
   "accessories":[
   ]
}`

**Comment by bxlouis** [comment]
Fixed with iOS 12 beta 4
