### ISSUE TITLE
Plugin keeps turning off TV with iOS 12.2 beta3

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#23]
After installing iOS 12.2 beta3, the TV keeps turning off automatically.
The problem disappeared when I removed the bravia-tvos platform from the config.json file so it seems that the problem comes from the plugin.

**Comment by SeydX** [comment]
Hey, im also on beta 3 and i dont have any issues with the plugin

Can u post your log when tv turns off automatically pls

**Comment by bxlouis** [comment]
OK I investigated the issue and it seems that it was linked to a script in Domoticz. I'll keep investigating and close the issue if I confirm it was caused by Domoticz.
