### ISSUE TITLE
New "View TV Settings" entry in Settings does not work

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#25]
It looks like iOS 12.2 beta 4 introduced a new "View TV Settings" entry in Settings (cf. screenshot). This button seems not to be supported yet.

![img_ddbed7ee5bd2-1](https://user-images.githubusercontent.com/4128333/53876067-4ef26280-4006-11e9-854e-adb1d3342832.jpeg)

**Comment by SeydX** [comment]
Added in next version, coming soon

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
