### ISSUE TITLE
Inputs are added as additional accessories

### ISSUE THREAD

**Issue by pbendersky** [SeydX/homebridge-bravia-tvos#26]
Using 12.2 released today. The input selector shows up empty, while inputs are shown as separate accessories instead.

Screenshots attached.
![IMG_1576](https://user-images.githubusercontent.com/1420884/54955907-6baaf780-4f2d-11e9-8816-33a2b28b171d.png)
![IMG_1575](https://user-images.githubusercontent.com/1420884/54955908-6baaf780-4f2d-11e9-9048-a9f11b41fb78.png)

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32

**Comment by pbendersky** [comment]
This worked fine in v3 the first time I used it. However, once I restarted homebridge to add Netflix as an input, all inputs were added as additional switches again.

**Comment by SeydX** [comment]
Can you force quit Apple Home app and open it again pls, normally after force quitting the app and reopening they must be gone

**Comment by pbendersky** [comment]
That worked! Thank you.
