### ISSUE TITLE
Android Oreo 8.0

### ISSUE THREAD

**Issue by KennyVB** [SeydX/homebridge-bravia-tvos#27]
Hello

Updated my Sony Bravia Android 55XF to android 8.0
now the update 12.2 for ios is here

i can't connect.

all other bravia for homebridge works. but none of your homebridge plugins i can get to work sadly

all of them writes this
 this one
```
[3/25/2019, 11:14:26 PM] [BraviaOSPlatform] [ERROR] TV: An error occured by getting system information, trying again...
[3/25/2019, 11:14:26 PM] [BraviaOSPlatform] [ERROR] Error: Failed to load data, status code:403
```

sorta the same the other ones you have write.. 
any help ? :)

**Comment by DR2000** [comment]
I just got it to run on 8.0 on X900F. Seems to work OK. 

The only issue I have is that if I put TV into automation to turn on and turn on Apple TV (input) it just goes to HDMI 2 where Apple TV is connected, but doesn't actually start Apple TV.

If I select AppleTV manually from the input list it works correctly. Any ideas?

**Comment by KennyVB** [comment]
How or what did you do to get it working ? 
 Tried homebridge now on:
Raspberry pi
Freebsd
macOs
No dice

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
