### ISSUE TITLE
Control centre remote doesn't work

### ISSUE THREAD

**Issue by maisun** [SeydX/homebridge-bravia-tvos#28]
Thanks for the plugin! It works great in Home app but in the remote from drop down control centre I cannot find the TV, what could be wrong?
Another question, can I remove all inputs like HDMI 1, 2 only keep Apple TV and fav apps?
Thank you in advance!

**Comment by DR2000** [comment]
And on option to set default on input would be nice.

**Comment by maisun** [comment]
Hi again,
After some search I found some discussion on the issue, looks like HomeKit only allows one TV per hub. 
See discussion here: https://github.com/nicoduj/homebridge-harmony/issues/54
And it looks like there will be a new API for TV service in HomeBridge 0.4.48, which should solve the problem. Appreciate if you could make the change to use the new API, thanks in advance!

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
