### ISSUE TITLE
ipadress to host

### ISSUE THREAD

**Issue by twocolors** [SeydX/homebridge-bravia-tvos#3]
many people use dhcp and don't know ip, maybe "host" config is more goon as "ipadress"

**Comment by SeydX** [comment]
Hello, i will add this to my todo list for v2

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: D <notifications@github.com>
Gesendet: Samstag, Februar 2, 2019 8:34 PM
An: SeydX/homebridge-bravia-tvos
Cc: Subscribed
Betreff: [SeydX/homebridge-bravia-tvos] ipadress to host (#3)


many people use dhcp and don't know ip, maybe "host" config is more goon as "ipadress"

**Comment by SeydX** [comment]
Should work in v2, if not feel free to reopen
