### ISSUE TITLE
tv select Dvbt not work status is off

### ISSUE THREAD

**Issue by twocolors** [SeydX/homebridge-bravia-tvos#30]
in log show

[3/29/2019, 1:46:32 AM] [BraviaOSPlatform] [INFO] TV: Start: Dvbc (5)
[3/29/2019, 1:46:39 AM] [BraviaOSPlatform] [WARN] TV: TV OFF <- when select Dvbt

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32

**Comment by SeydX** [comment]
See https://github.com/SeydX/homebridge-bravia-tvos/issues/32
