### ISSUE TITLE
iOS 12.3 Beta 2 - Upcoming changes

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-bravia-tvos#33]
With iOS 12.3, the following changes are coming to HomeKit regarding TV Accessory:

- It is no longer possible to select a specific input when the TV is off (see image)

<img src="https://user-images.githubusercontent.com/34152761/55802609-df760400-5ad8-11e9-89b9-b88e662ef4cd.png" width="50%" height="50%" />

**Comment by ayanm00** [comment]
Could you possibly add a way to not have the TV show up in the Apple TV Remote? I have an Apple TV and a Sony TV in my Living Room, and I want to be able to change the Input, but having two "Living Room" devices in the Remote app makes is cluttered. Love the plugin, by the way!

**Comment by bxlouis** [comment]
Could you provide more info regarding the customSpeaker parameter? It is not supported by iOS 12.2. Does it mean that Airplay 2 will be supported on existing TVs?

**Comment by SeydX** [comment]
@bxlouis 

the ‚Television Speaker Service’ is not supported atm by apple, therefore i have added custom speaker

With customSpeaker you are able to expose an alternative Axcessory as Speaker to HomeKit, eg Lightbulb or Speaker Service (Speaker Service is only visible in 3rd party apps like EVE etc)
