### ISSUE TITLE
doesn't work at all with oznu\docker-homebridge

### ISSUE THREAD

**Issue by coreybx** [SeydX/homebridge-bravia-tvos#4]
bombs out straight away at startup 

homebridge_1  | [2019-2-3 22:54:08] [TV] Initializing BraviaTVOS accessory...
homebridge_1  |
homebridge_1  | /homebridge/node_modules/homebridge-bravia-tvos/index.js:156
homebridge_1  |   this.Television=new Service.Television(self.name||'Television');
homebridge_1  |                   ^
homebridge_1  | TypeError: Service.Television is not a constructor
homebridge_1  |     at new BraviaTVOS (/homebridge/node_modules/homebridge-bravia-tvos/index.js:156:19)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (module.js:652:30)
homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
homebridge_1  |     at Module.load (module.js:565:32)
homebridge_1  |     at tryModuleLoad (module.js:505:12)
homebridge_1  |     at Function.Module._load (module.js:497:3)

**Comment by SeydX** [comment]
Which homebridge version?

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: coreybx <notifications@github.com>
Gesendet: Sonntag, Februar 3, 2019 12:58 PM
An: SeydX/homebridge-bravia-tvos
Cc: Subscribed
Betreff: [SeydX/homebridge-bravia-tvos] doesn't work at all with oznu\homebridge (#4)


bombs out straight away at startup

homebridge_1 | [2019-2-3 22:54:08] [TV] Initializing BraviaTVOS accessory...
homebridge_1 |
homebridge_1 | /homebridge/node_modules/homebridge-bravia-tvos/index.js:156
homebridge_1 | this.Television=new Service.Television(self.name||'Television');
homebridge_1 | ^
homebridge_1 | TypeError: Service.Television is not a constructor
homebridge_1 | at new BraviaTVOS (/homebridge/node_modules/homebridge-bravia-tvos/index.js:156:19)
homebridge_1 | at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
homebridge_1 | at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
homebridge_1 | at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
homebridge_1 | at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1 | at Module._compile (module.js:652:30)
homebridge_1 | at Object.Module._extensions..js (module.js:663:10)
homebridge_1 | at Module.load (module.js:565:32)
homebridge_1 | at tryModuleLoad (module.js:505:12)
homebridge_1 | at Function.Module._load (module.js:497:3)

**Comment by coreybx** [comment]
image: oznu/homebridge:1.7.9

**Comment by SeydX** [comment]
this plugin needs homebridge v0.4.46 and oznu/homebridge:1.7.9 has homebridge v0.4.45 installed, so it needs an update to v0.4.46 to work

**Comment by SeydX** [comment]
Closed.
