### ISSUE TITLE
Order of apps presented as TV inputs is different than what's specified in config.json

### ISSUE THREAD

**Issue by RMCob** [SeydX/homebridge-bravia-tvos#40]
Just updated to V3.0. My config.json entry is here:
      [foo.txt](https://github.com/SeydX/homebridge-bravia-tvos/files/3125443/foo.txt)
As you can see, the apps order is specified as "Netflix", "Prime Video", "ESPN", "Pandora", and "tinyCam PRO".
However, The apps shown in the list of TV inputs is in the order of "Prime Video", "Netflix", "tinyCam PRO", "ESPN", and "Pandora". Is there any way to reorder the list of inputs to match the config.json specification?
Besides this particular problem everything else seems to be working quite well.
Thanks in advance for your reply.....

**Comment by SeydX** [comment]
Will check this thx

**Comment by SeydX** [comment]
With next version the inputs are sorted alphabetically
