### ISSUE TITLE
TV shuts down when Homebridge restarts

### ISSUE THREAD

**Issue by Sammy990** [SeydX/homebridge-bravia-tvos#41]
Hi, I have two issues on the V3 of the Bravia Plugin:

1. When homebridge restarts or I restart my Pi and the TV is currently turned on, the TV turns off when the plugin loads on homebridge startup.

2. I‘m not longer able to turn my TV on. MAC is correct and WOL is set to true. However I‘m able to turn the TV on. I also tried the previous old dynamic plugin which is not based on the new HomeKit TV Service and it still can turn the tv on. But the new plugin is not able to do. This and issue number one started to appear after I uninstalled V2 and installed V3

Thanks

**Comment by SeydX** [comment]
@Sammy990 

Have you tried without WOL? (wol=false)

**Comment by Sammy990** [comment]
Works now! Thanks!
