### ISSUE TITLE
Can this work with Non Android Sony Bravia

### ISSUE THREAD

**Issue by adavison007** [SeydX/homebridge-bravia-tvos#42]
Hi, Has anyone tried this with a non Android Sony Bravia TV? be keen to know before giving it a go.

**Comment by bkonings** [comment]
Unless they implement the Sony API that won't work.

**Comment by adavison007** [comment]
@bkonings Do you know if it does, or is the only way to find out try it?

**Comment by bkonings** [comment]
It is highly unlikely to work, the API is a specific solution by Sony as far as I can tell.

**Comment by adavison007** [comment]
> It is highly unlikely to work, the API is a specific solution by Sony as far as I can tell.

@bkonings it is a 2017 Sony Bravia TV, it just isn't Android based.... do you think its worth a go?

**Comment by bkonings** [comment]
I think you will fail doing this step, so check if you can do it:

https://github.com/SeydX/homebridge-bravia-tvos#preparing-the-tv-psk

**Comment by SeydX** [comment]
@adavison007 

If you have options for ip control or psk, just try it
