### ISSUE TITLE
TV appears in default room whenever homebridge is restarted

### ISSUE THREAD

**Issue by lucaponzanelli** [SeydX/homebridge-bravia-tvos#43]
Whenever homebridge is restarted, TVs appear in the default room, and get removed from all scenes, and all preferences for inputs are lost as if they were removed and then re-added to HomeKit. On the other hand, the speaker preserves all the options as expected after restarting homebridge.

This is the configuration I'm using:

```json
    {
      "platform": "BraviaOSPlatform",
       "interval": 10,
      "tvs": [
        {
          "name": "Sony Bravia",
          "ip": "....",
          "mac": "....",
          "wol": true,
          "port": 80,
          "psk": "....",
          "customSpeaker": true,
          "speakerType": "speaker",
          "extraInputs": true,
          "cecInputs": true,
          "channelInputs": ["DVBC"],
          "channels": [ ... ],
          "apps":[ ... ]
        }
      ]
    }
```

**Comment by SeydX** [comment]
How many TVs u have in your setup?

**Comment by lucaponzanelli** [comment]
just one

**Comment by SeydX** [comment]
@lucaponzanelli 

Hmmm, anything to see in the log?

**Comment by lucaponzanelli** [comment]
Logs seems to be fine. The only warning I get concerns the version of NodeJs (I'm running node 10). 
If it might help, I'm running homebridge on docker (https://github.com/oznu/docker-homebridge).

**Comment by SeydX** [comment]
Maybe a pairing issue? Can u remove from HK and re add pls

**Comment by lucaponzanelli** [comment]
ok, I might have found the problem. In homebridge configuration I was deleting `accessories/cachedAccessories` at startup to make cmd2switch properly work.

Apparently, if the cache is deleted as I was doing, the TV is recreated from scratch without the preferences that have been assigned to the accessory via HomeKit (e.g., room, hidden channels).

**Comment by SeydX** [comment]
@lucaponzanelli 

Yea its a dynamic platform plugin, the latest homebridge api, so the accessories are always stored in cachedAccessories and if u remove this, the accessory will be resetted or recreated

So its not an issue of this plugin, closing now
