### ISSUE TITLE
channels and apps

### ISSUE THREAD

**Issue by rmoya87** [SeydX/homebridge-bravia-tvos#48]
hello

First thanks for your work, amazing.

Everything work but If I try config channels and apps display on home app but like active on gray and its not working, could you tell me if I am doing something wrong?

This is my config:
        {
            "platform": "BraviaOSPlatform",
            "tvs": [
                {
                    "name": "Televisión",
                    "ip": "XXX.XXX.X.XX",
                    "port": 80,
                    "psk": "XXXXXXX",
                    "wol": true,
                    "channels": [
                        {
                            "channel": 1,
                            "source": "TVE"
                        },
                        {
                            "channel": 2,
                            "source": "2"
                        }
                    ],
                    "apps": [
                        "YouTube",
                        "Netflix"
                    ]
                }
            ],
            "interval": 10
        },

**Comment by SeydX** [comment]
What u mean with active on gray? Can u post a screenshot and your log pls

**Comment by SeydX** [comment]
Is TVE given by your tv? Can u post ur whole log pls

**Comment by SeydX** [comment]
@rmoya87 

btw v3.0.6 is online

**Comment by rmoya87** [comment]
Hello my problem is (I think is my wrong): if I have this config:
{
"platform": "BraviaOSPlatform",
"tvs": [
{
"name": "Televisión",
"ip": "XXX.XXX.X.XX",
"port": 80,
"psk": "XXXXXXX",
"wol": true,
"channels": [
{
"channel": 1,
"source": "TVE"
},
{
"channel": 2,
"source": "2"
}
],
"apps": [
"YouTube",
"Netflix"
]
}
],
"interval": 10
},

Don't display apps and channels in inputs.

But if I have this:
{
"platform": "BraviaOSPlatform",
"tvs": [
{
"name": "Televisión",
"ip": "XXX.XXX.X.XX",
"port": 80,
"psk": "XXXXXXX",
"wol": true,
"apps": [
"YouTube",
"Netflix"
]
}
],
"interval": 10
},

I can see in inputs apps and works.

So I thinks something is wrong to me.
For example in my tv channel 001 call TVE but I have to type 1 in channel right? could you tell me if I am doing something wrong?

thanks

**Comment by rmoya87** [comment]
![IMG_73E89C6855AD-1](https://user-images.githubusercontent.com/28694040/57017217-750b3c00-6c1e-11e9-9a34-0d3d304a480d.jpeg)
Attach picture.
This is my config now:
        {
            "platform": "BraviaOSPlatform",
            "tvs": [
                {
                    "name": "Televisión",
                    "ip": "XXXXX",
                    "port": 80,
                    "psk": "XXXX",
                    "wol": true,
                    "channels": [
                        {
                            "channel": 1,
                            "source": "La 1 HD"
                        },
                        {
                            "channel": 2,
                            "source": "La 2"
                        }
                    ],
                    "apps": [
                        "YouTube",
                        "Netflix"
                    ]
                }
            ],
            "interval": 10
        },

**Comment by rmoya87** [comment]
if I remove channels apps will be on inputs but again I think problem are channels because don't display it too

**Comment by SeydX** [comment]
@rmoya87 

Di Inputs you posted in the screenshot will disappear after force quitting the home app

Yes, you need to start with 1, not 001

Can u post your Log

**Comment by ticky** [comment]
I briefly had this issue with the plugin, but it resolved itself after restarting Homebridge and also the Home app, so unfortunately I can’t get logs. I wonder if it’s a first-run issue?

**Comment by huongminh** [comment]
I have the same issue with channel. if I add channel in the config.json then I see no channel in the input and all apps would be out on screen as separate accessories. the log shows:
[BraviaOSPlatform] [INFO] Sony TV: Checking Inputs for DVBT! Other channel sources are not considered!
Oct 30 01:15:21 raspberrypi homebridge[24993]: [10/30/2019, 1:15:21 AM] [BraviaOSPlatform] [ERROR] Sony TV: An error occured while handling accessories!

my config.json:
"platform": "BraviaOSPlatform",
     "tvs": [
       {
         "name": "Sony TV",
         "ip": "192.168xxxx",
         "mac": "04:5d:xxxx",
         "port": 80,
         "psk": "xxxxxx",
         "cecInputs": false,
         "channelInputs": ["DVBT"],
          "channels": [
            {
              "channel":800,
              "source":"DVBT"
            },
            {
              "channel":801,
              "source":"DVBT"
            },
            {
              "channel":802,
              "source":"DVBT"
            },
            {
              "channel":805,
              "source":"DVBT"
            }
          ],
         "apps": [
                   "YouTube",
                   "Netflix",
                   "Kodi"
                 ]
       }
     ],
     "interval": 10
      },

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
