### ISSUE TITLE
Node Version Error

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [SeydX/homebridge-bravia-tvos#5]
09:07:14] ---
Feb 03 09:07:14 Bridge homebridge[8808]: [2019-2-3 09:07:14] Plugin /usr/local/lib/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v9.9.0. You may need to upgrade your installation of Node.
Feb 03 09:07:14 Bridge homebridge[8808]: [2019-2-3 09:07:14] Loaded plugin: homebridge-bravia-tvos

**Comment by SeydX** [comment]
Can u send me the whole log pls and not only the node warning

**Comment by SeydX** [comment]
Update to latest available node version
