### ISSUE TITLE
On Off switch

### ISSUE THREAD

**Issue by det-box** [SeydX/homebridge-bravia-tvos#50]
Hi SeydX, 
I have now switched to this plugin, Unfortunately, the device is not seen in a third-party APP.
I only see the "Sony TV Speaker" switch. 
Is it possible to show the on / off switch separately? 
So you can use this in scenes. 
Thank you
det

**Comment by SeydX** [comment]
@det-box 

Apple is currently blocking 3rd party apps from controlling the television accessories

But good suggestion, i will add this as an enhancement to my list (off/on as switch accessory)
