### ISSUE TITLE
Hide inactive entries from Input

### ISSUE THREAD

**Issue by angelflames1337** [SeydX/homebridge-bravia-tvos#54]
Tried to untick the box in the Home app, and that works. But after restarting homebridge they appear again in the list. 

From other post, seems like the Elgato Eve app suppose to fix this, but my TV doesn't appear in the app at all. 

Not sure if this is a bug or intended.

**Comment by SeydX** [comment]
3rd party apps can not access the TV accessory because apple is blocking it
