### ISSUE TITLE
Ability to Disable Control Center Remote

### ISSUE THREAD

**Issue by ayanm00** [SeydX/homebridge-bravia-tvos#55]
Hey SeydX,

First off, thank you for making this awesome plugin! I use it all the time to control my TV's power status through Siri. Could you possibly add a way to disable the control center remote for the Bravia TV. I have an Apple TV connected with my Bravia, and people in my house get confused as to which device to control when they see two devices with similar names in the Control Center Remote list.

Thanks!

**Comment by SeydX** [comment]
@ayanm00 

it is not possible to remove the TV accessory from remote controll
