### ISSUE TITLE
Apps is gray 

### ISSUE THREAD

**Issue by GaoVang2005** [SeydX/homebridge-bravia-tvos#56]
so this is the same issue as rmoya87 i dont see you fix that so i post this as a new issue
so i add "apps":[
"Youtube"
"Spotify"
] 
to my config 
just Spotify show in home app but gray and actived
so how to fix that and can we put apps into inputs option of the TV ?

**Comment by SeydX** [comment]
Try "YouTube"

and gray inputs in home ap cann be fixed with force quitting home app

**Comment by GaoVang2005** [comment]
well force quitting home app doenst fix the problem but by some how now apps go into the input option and can work perfectly
Thank SeydX for great plugin for homebridge

**Comment by GaoVang2005** [comment]
oh and can you add home button to the remote in  the control center and how to talk to siri to change input to HDMI 1 or somethings
i said set the tv input to HDMI doesnt work
And when i turn up volume through siri doenst work either
