### ISSUE TITLE
Feature request: register all TVs as external accessories

### ISSUE THREAD

**Issue by maisun** [SeydX/homebridge-bravia-tvos#58]
Readme says:
If you have added multiple TVs to homebridge via this plugin, please note that all TVs except the first one will be published as "external accessories”

Can we have an option to allow first TV also registered as external device? I ask because I use other TV plugins which don’t support external accessory.
Thank you in advance!

**Comment by maisun** [comment]
Any suggestion?

**Comment by SeydX** [comment]
Hey, will be added in the next version

**Comment by maisun** [comment]
Great, thank you!

**Comment by SeydX** [comment]
Sorting out the issues. Added in v4 (coming soon)
