### ISSUE TITLE
Add scene select (or Picture Mode) settings

### ISSUE THREAD

**Issue by ndlaham** [SeydX/homebridge-bravia-tvos#59]
I have been trying to figure out a way to assign the picture mode (cinema home, cinema pro, sports, game, etc..) through IP control (IRCC codes and REST API) but cannot figure out how to do it. There is actually an IRCC code dedicated to PictureMode AAAAAQAAAAEAAABkAw== (which I assume just brings that menu up), but I have never been able to get it to work for my TV. Others have reported differently. 
I can get most of the other IRCC codes to respond so it may be that my TV is not compatible with that particular code. There is also a code for Action Menu which saves some time to get into the Picture Mode settings, but the user still has to navigate through the menus to change the picture mode at the end of the day. When switching between movies, sports or gaming this tends to get annoying and I have to get my sony remote out from the drawer so I’m determined to figure something out, hopefully with some help from smarter people.

I have to believe there is a way to set the picture mode using the REST API. I found documentation on a method called setSceneSetting which describes putting the TV into auto 24p mode (which when turned on, normally switches from any picture mode to home cinema when it detects 24fps film content), so I am thinking if this can get added to this plugin successfully, perhaps there are other values that can get passed through this method and actually set the picture mode the user wants as well

Even having the ability to turn on auto24pSync would be nice if nothing else, so I’m hoping you could look into that functionality and if that works maybe we can all dig a bit deeper.

See below on Sony resources regarding this -

Thanks in advance for any feedback! 

https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/videoscreen/v1_0/setSceneSetting/index.html

**Comment by ndlaham** [comment]
I saw some similar logic on this issue for a home assistant integration that may help. 

https://github.com/custom-components/media_player.braviatv_psk/issues/14

**Comment by SeydX** [comment]
Sorting out the issues. Added in v4 (coming soon)
