### ISSUE TITLE
Can’t automate power

### ISSUE THREAD

**Issue by paqpaqpaq** [SeydX/homebridge-bravia-tvos#6]
Since the plugin only presents a Home app switch for on/off and input selector, there is no power selector in other apps. 
This way the power cannot be automated; not even in Home app. 

Could that be solved?

**Comment by SeydX** [comment]
which iOS version u have?

**Comment by paqpaqpaq** [comment]
12.2

It took 3 Homebridge crashes (thank god for back-ups) to have it show all switches.
Eventually also the power switch! (in scenes and automations)

In between two homebridge crashes the apps in the config.json showed up as houses that did nothing.
In the end it took several new bindings between homekit and homebridge to get everything working.

**Comment by Sammy990** [comment]
I had the same experience and realized it seems currently it’s mandatory to be on the same network (WiFi) with your iOS device when you first time run the plugin. If you’re not, all apps inputs etc appears not to be recognized as part of the tv accessory and are reported as separate unusable switches with Anhöhe icon in the Home app.

Can’t await to see a V2 of this plugin for more automations and more dynamically!
Thanks @SeydX

**Comment by paqpaqpaq** [comment]
I was always on the same Wifi during my installations.
More likely it is within syncing errors between icloud and homebridge (persist) folders.

**Comment by SeydX** [comment]
version 2.0 is out and fix several bugs like this one, give it a try
