### ISSUE TITLE
Sony Z9d cecinputs: true breaks this 

### ISSUE THREAD

**Issue by janthony6** [SeydX/homebridge-bravia-tvos#61]
if you turn this on with this tv, it breaks and drops connectivity.  error below.
result is the tv now lists 4 icons in the home app for HDMI 1, 2, 3, 4.  All of which do nothing.  Once you remove cecinputs from config, it works again but you can't delete those HDMI tiles and you can no longer select from the tv.

[ERROR] Great Room TV: An error occured while handling accessories!
[6/2/2019, 15:52:09] [BraviaOSPlatform] [ERROR] {
    "status": 500,
    "message": "Internal Server Error",
    "config": {
        "transformRequest": {},
        "transformResponse": {},
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "X-Auth-PSK": "control4",
            "User-Agent": "axios/0.18.1",
            "Content-Length": 78
        },
        "method": "post",
        "url": "http://10.0.0.129:80/sony/avContent",
        "data": "{\"id\":1,\"method\":\"getCurrentExternalInputsStatus\",\"version\":\"1.0\",\"params\":[]}"
    },
    "data": {
        "error": [
            500,
            "Internal Server Error"
        ],
        "id": 1
    }
}

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
