### ISSUE TITLE
Erroneous error msg regarding node version

### ISSUE THREAD

**Issue by RMCob** [SeydX/homebridge-bravia-tvos#62]
I realize this is only cosmetic, but you have been ignoring this for quite a while.... :-)

[6/3/2019, 4:43:26 PM] Plugin /usr/lib/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v12.3.1. You may need to upgrade your installation of Node.

**Comment by RMCob** [comment]
I apologize. After further research I realize that this message is coming from homebridge, not your plug-in. Since your package.json looks correct it must be their issue and I will pursue it with them.

**Comment by Jafalex** [comment]
> I apologize. After further research I realize that this message is coming from homebridge, not your plug-in. Since your package.json looks correct it must be their issue and I will pursue it with them.

Hi, sorry I know this may not be related to this plugin in particular, however I only get this warning when using homebridge-bravia-tvos. Can you please point me in the right direction to get rid of it? Thanks!
