### ISSUE TITLE
Custom speaker

### ISSUE THREAD

**Issue by royale56** [SeydX/homebridge-bravia-tvos#64]
Is the speaker type “speaker” not supported by HomeKit? I see it showing up but not working. When I switch the type to bulb or light it seems to work ok

**Comment by fizulnizam** [comment]
Any solution to the problem that you faced? I am having the same issue right now

**Comment by royale56** [comment]
I stopped using this plugin as it hasn’t been updated in over a year. I’ve switched to this one but it does not have a bulb to adjust your volume -
https://www.npmjs.com/package/homebridge-bravia
