### ISSUE TITLE
Volume control with soundbar

### ISSUE THREAD

**Issue by royale56** [SeydX/homebridge-bravia-tvos#65]
Without the sound bar my volume control works just fine but when I turn the sound bar on and try to adjust the volume it moves the volume sluggishly and only goes 1-4 levels at a time. For example if the volume is set to 10 on the tv and I try to raise it to 20 it might only move to 14. Is there a way to fix this?

The tv is the x900e and the sound bar is the htx9000f.

**Comment by SeydX** [comment]
Yeah thats a known bug and will be fixed soon

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem
