### ISSUE TITLE
change from DVBT to DVBC dont work

### ISSUE THREAD

**Issue by KennyVB** [SeydX/homebridge-bravia-tvos#66]
hello

changed the configfile from DVBT to DVBC and changed the numbers to match
opon restart the log still says it reads DVBT?!?!

`0|homebridge  | [6/13/2019, 10:03:10 PM] [BraviaOSPlatform] [INFO] TV Speaker: Authenticated!
0|homebridge  | [6/13/2019, 10:03:10 PM] [BraviaOSPlatform] [INFO] TV: Authenticated!
0|homebridge  | [6/13/2019, 10:03:10 PM] [BraviaOSPlatform] [INFO] TV: CEC detected, checking TV state before fetching inputs...
0|homebridge  | [6/13/2019, 10:03:10 PM] [BraviaOSPlatform] [INFO] TV: TV on! Fetching inputs...!
0|homebridge  | [6/13/2019, 10:03:18 PM] [BraviaOSPlatform] [INFO] TV: Checking Inputs for DVBT! Other channel sources are not considered!
0|homebridge  | [6/13/2019, 10:03:18 PM] [BraviaOSPlatform] [INFO] TV: Inputs Finished!`

`{
  "platform": "BraviaOSPlatform",
  "tvs": [
    {
      "name": "TV",
      "ip": "10.0.2.12",
      "port": 80,
      "extraInputs": false,
      "cecInputs": true,
      "channelInputs": ["DVBC"],
      "channels": [
             {
               "channel":2,
               "source":"DVBC"
             },
             {
               "channel":6,
               "source":"DVBC"
             },
{
               "channel":28,
               "source":"DVBC"
             },
{
               "channel":8,
               "source":"DVBC"
             }
  ],
      "mac": "CC:98:8B:4B:C5:CA",
      "apps": [
                        "YouTube",
                        "Plex",
                        "Netflix",
                        "TV 2 PLAY"
                        ],
       "wol": false,
       "customSpeaker": true,
       "speakerType": "lightbulb"
    }
  ],
  "interval": 10
}`

**Comment by SeydX** [comment]
It seems that your tv is not able to check dvbc

```
TV: Checking Inputs for DVBT! Other channel sources are not considered!
```
