### ISSUE TITLE
TVs don't appear as accessories in the Home app

### ISSUE THREAD

**Issue by cstromme** [SeydX/homebridge-bravia-tvos#67]
Just installed this plugin, and got it to successfully authenticate with 2 of my Sony TVs, but for some reason they won't show up in the Home app. Checked the homebridge hub in the home app and it lists my other accessory, but none of the TVs.

This is what I've added to my config.json file:
```
  "platforms": [
   {
     "platform": "BraviaOSPlatform",
     "tvs": [
       {
         "name": "sonytvstue",
         "ip": "192.168.1.93",
         "port": 80,
         "customSpeaker": true,
         "cecInputs": true
       },
       {
         "name": "sonytvoffice",
         "ip": "192.168.1.59",
         "port": 80
       }
     ],
     "interval": 10
   }
  ]
```

And this is from my logs:

> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] Adding new accessory: sonytvstue
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvstue: Initalizing Bravia API with IP Control
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvstue: Cheking authentication...
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] Adding new accessory: sonytvstue Speaker
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvstue Speaker: Cheking authentication...
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvoffice: Initalizing Bravia API with IP Control
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvoffice: Cheking authentication...
> [6/22/2019, 11:43:24 PM] Homebridge is running on port 53793.
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvstue: sonytvstue.json refreshed with new cookie!
> [6/22/2019, 11:43:24 PM] [BraviaOSPlatform] [INFO] sonytvoffice: sonytvoffice.json refreshed with new cookie!
> [6/22/2019, 11:43:29 PM] [BraviaOSPlatform] [INFO] sonytvstue: Authenticated!
> [6/22/2019, 11:43:29 PM] [BraviaOSPlatform] [INFO] sonytvstue: CEC detected, checking TV state before fetching inputs...
> [6/22/2019, 11:43:29 PM] [BraviaOSPlatform] [INFO] sonytvoffice: Authenticated!

Any idea why these TVs won't show up as accessories?

**Comment by iuliusmaximilian** [comment]
+1

**Comment by wouterpotters** [comment]
You have to manually add these tv's. See also: https://github.com/SeydX/homebridge-bravia-tvos#multiple-tvs

**Comment by cstromme** [comment]
How do you manually add them? If I try to add an accessory it doesn’t list it, and I need the code for the accessory to add it. Looked through the logs and the various files that Homebridge produces, but doesn’t seem to be a code for these accessories anywhere.

**Comment by wouterpotters** [comment]
I don’t have two tv’s, so no way to test it here. I hope someone else can answer your question.

Best,
Wouter

**Comment by cstromme** [comment]
Figured it out here. Have to add `"tvs": true` to the bridge section. Then it works without having to add anything manually.

**Comment by aragans02** [comment]
Where are you meant to add the “tvs”: true to the config?
