### ISSUE TITLE
"An error occurred while handling accessories"

### ISSUE THREAD

**Issue by ErickJR13** [SeydX/homebridge-bravia-tvos#68]
Environment: macOS Mojave 10.14.6, Sony Bravia XBR65X850E (2017, 65")

Values in json edited for privacy

config.json: 

`	"platforms": [

		{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"sudo": false
		},

		{
			"platform": "BraviaOSPlatform",
			"tvs": [{
				"name": "TV",
				"ip": "IP address",
				"mac": "mac with uppercase letters",
				"port": 80,
                                "wol":true,
				"psk": "key",
				"extraInputs": false,
				"cecInputs": true

			}]
		}
	]

}
`

Not sure what's going on. The TV has constant access to the internet. I'm trying to set this up even while having the TV do some activity with the Internet. Authentication is set to "Normal and Pre-Shared Key", IP Control is enabled, Remote Start is enabled. How can I solve this?

**Comment by SeydX** [comment]
Try v3.0.7 pls
