### ISSUE TITLE
Motion Sensor based on App/Channel or state

### ISSUE THREAD

**Issue by rogerveijk** [SeydX/homebridge-bravia-tvos#70]
This is a sort feature request, like you created the chromecast status switch to trigger automations.

E.g. Netflix app is open (or plays content) trigger a automation (example dim hue lights).

Best would be to only create a motion sensor for a specific app/channel, since regular tv channels for example shouldn’t tigger anything in my situation.

The benefit of adding a motion sensor is your automations will even be triggered when the tv is controlled by a regular remote (instead of by Siri).

**Comment by SeydX** [comment]
Atm it is not possible to detect which app is running due to the API
