### ISSUE TITLE
TV does not always appear as remote on iOS 13+

### ISSUE THREAD

**Issue by bxlouis** [SeydX/homebridge-bravia-tvos#72]
Hi,

Using iOS 13.2, the Sony TV does not always appear in the remote quick menu (cf. screenshot).
It used to work like a charm before iOS 13.

![IMG_1DA4F35780CB-1](https://user-images.githubusercontent.com/4128333/68863539-dcd33100-06ef-11ea-8397-de8a8ace8c50.jpeg)

**Comment by rogerveijk** [comment]
I have this issue too. Sometimes it works, sometimes you have to close and try again a few minutes later. 
Doe anyone know how to fix this?

**Comment by bxlouis** [comment]
@SeydX seems you are not working on this project anymore. Could you please take time to tell if there will be updated in the future? 
Thanks!

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by bxlouis** [comment]
Hi @SeydX awesome to get news from you and the v4! I’ll stay tuned to test this when it’s out!

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
