### ISSUE TITLE
TV is not power off and on

### ISSUE THREAD

**Issue by pl-samurai** [SeydX/homebridge-bravia-tvos#74]
This plugin is not working. Homekit Show sources, i pair with picode and add to tv.json but when i click on or off tv is not power on or off.

**Comment by pl-samurai** [comment]
[BraviaOSPlatform] [ERROR] {
    "status": 403,
    "message": "Forbidden",
    "config": {
        "transformRequest": {},
        "transformResponse": {},
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "X-Auth-PSK": "key",
            "User-Agent": "axios/0.18.1",
            "Content-Length": 78
        },
        "method": "post",
        "url": "http://192.192.192.102:80/sony/system",
        "data": "{\"id\":1,\"method\":\"setPowerStatus\",\"version\":\"1.0\",\"params\":[{\"status\":false}]}"
    },
    "data": {
        "auth_url": {
            "default": "http://192.192.192.102/sony/webauth/auth_default"
        }
    }
}

**Comment by pl-samurai** [comment]
I chceck - turn on is working but turn off not. I can show menu on tv from homekit but i cant change source - but i see my sources.

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
