### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by iGodPhil** [SeydX/homebridge-bravia-tvos#75]
While the plugin want to fetch the CEC inputs i get this internal server error and don't know how to handle it. Maybe someone can help me. 

> [2020-2-25 0:34:32] [BraviaOSPlatform] [ERROR] Sony TV: An error occured while handling accessories!
> [2020-2-25 0:34:32] [BraviaOSPlatform] [ERROR] {
>     "status": 500,
>     "message": "Internal Server Error",
>     "config": {
>         "transformRequest": {},
>         "transformResponse": {},
>         "timeout": 0,
>         "xsrfCookieName": "XSRF-TOKEN",
>         "xsrfHeaderName": "X-XSRF-TOKEN",
>         "maxContentLength": -1,
>         "headers": {
>             "Accept": "application/json, text/plain, */*",
>             "Content-Type": "application/json",
>             "Cookie": "auth=D043A09AD9497CFE42E37281357B57825DA4046D",
>             "User-Agent": "axios/0.18.1",
>             "Content-Length": 78
>         },
>         "method": "post",
>         "url": "http://192.168.178.30:80/sony/avContent",
>         "data": "{\"id\":1,\"method\":\"getCurrentExternalInputsStatus\",\"version\":\"1.0\",\"params\":[]}"
>     },
>     "data": {
>         "error": [
>             500,
>             "Internal Server Error"
>         ],
>         "id": 1
>     }
> }
>

**Comment by RogerSelwyn** [comment]
This seems to be a problem of the TV, since I get that error when calling from Postman

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
