### ISSUE TITLE
package.json needs to be updated.

### ISSUE THREAD

**Issue by RMCob** [SeydX/homebridge-bravia-tvos#80]
Due to the latest updates to homebridge and node, the dependencies shown in package.json for "engines" needs to be updated to eliminate error messages in the log file. For testing purposes I changed the values to "homebridge": "^1.0.0", "node": "^12.0.0", and the error messages went away. These changes need to be made in the official version.

**Comment by bkonings** [comment]
I made some changes and now the TV looks funny in the homekit app, channel selections have become on off switches that all have the state on. Perhaps more is needed besides the dependency updates.

**Comment by SeydX** [comment]
Fixed
