### ISSUE TITLE
Second TV not working after upgrading to Homebridge 1.0.4

### ISSUE THREAD

**Issue by fcoura** [SeydX/homebridge-bravia-tvos#82]
Hey @SeydX, this is a great plugin. Thank you for all the hard work. Also just wanna report that it’s broken to me as well - right after updating the Homebridge to 1.0.4 and node.js to 10.17.0 the second TV is not responsive anymore. I deleted it from the home.app and tried to add it again, but it’s not showing anymore. Hope you have the time to fix it. Whole community here looking forward for it :) Thank you once again.

**Comment by Sammy990** [comment]
same here, hopefully @SeydX got time to update this plugin - as it is incredible cool

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
