### ISSUE TITLE
KDL Network Timeout

### ISSUE THREAD

**Issue by Ledbetter14** [SeydX/homebridge-bravia-tvos#83]
I've got a problem with my KDL55W800A. It works great with the plugin but seems to stop responding to network requests (ie turn on) after awhile in standby and goes "No Response". This unfortunately hangs everything in that Homebridge instance. Turning the TV on manually fixes everything without a Homebridge restart. Is this expected behaviour of the older models? I don't have any TV settings relating to Eco or Network that help. I'm trying to nail down how long it takes to stop responding but it's a work in progress. My very crude idea is just to try to turn it on & off before the time period using a RM Mini 3 I have in the room but I would love something a bit more elegant if possible?

**Comment by SeydX** [comment]
How is your TV connected to the network? Wifi?
