### ISSUE TITLE
iOS 14: Issue with icon in Homekit

### ISSUE THREAD

**Issue by maisun** [SeydX/homebridge-bravia-tvos#84]
Hi,
After upgrading to iOS 14, I noticed in HomeKit the TV icon is replaced by a "house" icon. The plugin still works fine though. Anybody experience the same problem?

**Comment by jang-uk** [comment]
same here

**Comment by maisun** [comment]
I have tried to re-add it (and clean cache before) and same result. My other plugins for harmony and samsung tizen work fine and show the right tv icon

**Comment by maisun** [comment]
See here:
https://github.com/nicoduj/homebridge-harmony/issues/298

**Comment by jang-uk** [comment]
> See here:
> [nicoduj/homebridge-harmony#298](https://github.com/nicoduj/homebridge-harmony/issues/298)
> Looks like the solution is to publish as external accessory

wow! IT DID WORK!

**Comment by Sammy990** [comment]
Seems the behavior is still the same with 14.2 Beta 2. @SeydX : Would it make sense to change the plug-in behavior to expose all TV‘s, also the first one, as external accessories by default?

**Comment by maisun** [comment]
> Seems the behavior is still the same with 14.2 Beta 2. @SeydX : Would it make sense to change the plug-in behavior to expose all TV‘s, also the first one, as external accessories by default?

I requested that long time ago, would be nice as some other plugins only expose internal, and each HB only allows one internal TV.

**Comment by ceraz68** [comment]
> wow! IT DID WORK!

Hi can you explain the steps because I tried changing the config.json file but it didn't work.

So I did the hard way ... uncommented lines 99-107 in the code of homebridge-bravia-tvos/src/accessory.js. Can't see where 'external' can be set by the config.json

**Comment by paqpaqpaq** [comment]
> @jang-uk
> 
> > wow! IT DID WORK!
> 
> Hi can you explain the steps because I tried changing the config.json file but it didn't work.
> 
> So I did the hard way ... uncommented lines 99-107 in the code of homebridge-bravia-tvos/src/accessory.js. Can't see where 'external' can be set by the config.json

even that doesn't work for me; I keep on getting errors that the device is already in use and restarts

**Comment by ceraz68** [comment]
@paqpaqpaq

If you did what I did (i.e. uncommenting the lines in the code) make sure that you empty the homebridge cache.

If using config-ui-x click "homebridge settings" from the top right and select "Remove Single Cached Accessory", remove the cache for the TV and then restart.

**Comment by paqpaqpaq** [comment]
> @paqpaqpaq
> 
> If you did what I did (i.e. uncommenting the lines in the code) make sure that you empty the homebridge cache.
> 
> If using config-ui-x click "homebridge settings" from the top right and select "Remove Single Cached Accessory", remove the cache for the TV and then restart.

Unfortunately this is the outcome.
```
[2020-10-29 16:55:11] [BraviaOSPlatform] [INFO] TV: Checking Inputs for DVBT! Other channel sources are not considered!
[2020-10-29 16:55:11] [BraviaOSPlatform] [INFO] TV: New Inputs fetched. Turning off TV again.
[2020-10-29 16:55:11] [BraviaOSPlatform] [WARN] TV: Removing Input: Woonkamer
[2020-10-29 16:55:11] [BraviaOSPlatform] [INFO] TV: Inputs Finished!
[2020-10-29 16:55:12] [BraviaOSPlatform] [INFO] Registring external accessory: TV
[2020-10-29 16:55:12] [BraviaOSPlatform] [ERROR] TV: An error occured while handling accessories!
[2020-10-29 16:55:12] [BraviaOSPlatform] [ERROR] {}
```

Also, I don't have the option of removing a single cached item.

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
