### ISSUE TITLE
Not all inputs appearing (Bravia KDL Model)

### ISSUE THREAD

**Issue by ursusHU** [SeydX/homebridge-bravia-tvos#85]
Hi,
I have a KDL50W815B, which I must say until now works only with your Plugin correctly on long term. 
I have only a small annoying issue. In the inputs menu only HDMI4 and my ATV Cec device appears, and I miss Hdmi2 & 3. Is there a setting I should modify? Thanks in advance.
My config:
{
            "platform": "BraviaOSPlatform",
            "tvs": [
                {
                    "name": "Living Room Television",
                    "ip": "192.168.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "port": 80,
                    "psk": "xxxx",
                    "cecInputs": true,
                    "wol": true
                }
            ],
            "interval": 10
        }

**Comment by SeydX** [comment]
Currently working on v4 and there will be some major changes, should fix this problem

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed in v4 (coming soon)
