### ISSUE TITLE
Version 4 Beta

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-bravia-tvos#86]
Hey guys,

i am currently working on the 4th version of the plugin and have already fixed many of the bugs that you have encountered. There are also some new features.

## Changelog (2020-11-4)

- Refactored code
- BETTER: Authetication flow
- BETTER: Reduced cpu/ram usage
- BETTER: Detection for tv inputs
- NEW: IRCC commands as inputs
- NEW: Config UI X support
- NEW: Speaker types (switch, lightbulb, speaker)
- NEW: Customizable Apple Remote Commands
- Bugfixes

**BRAKING CHANGES:** If you use v3 of this plugin, please remove the added TV from Homekit/Homebridge before updating! Otherwise you have to reset Homebridge!

## Beta Test

If you want to test the version you can use the following command:

``sudo npm i -g --unsafe-perm homebridge-bravia-tvos@beta``

You also install the bravia module:

``sudo npm i -g --unsafe-perm @seydx/bravia@latest``

**Attention:** The new version is not compatible with version < 4! Due to the Config UI X integration I had to change the config.json! If u running v3, u need to remove it from homebridge/homekit.

## Debugging & Bugs & Enhancements

Please enable "**Debug**" under Configuration before testing the beta version. If you have any bugs, suggestions for improvement or other ideas, you can write it here.

## Example Config

- [Example BASIC Config](https://github.com/SeydX/homebridge-bravia-tvos/tree/beta#example-basic-config)
- [Example FULL Config](https://github.com/SeydX/homebridge-bravia-tvos/blob/beta/example-config.json)

Have fun testing 👍🏼 

# !!Version 4.0 is online now!!

**SeydX**

**Comment by bkonings** [comment]
Hi, if I add HDMI as "extInput:hdmi" the HDMI inputs are added as switches under the TV.
In the version 3 I can select what input to show in the home app, seems this is not possible in version 4.
Version 3
![IMG_4837](https://user-images.githubusercontent.com/2129013/98224188-788a2c80-1f53-11eb-812e-8da607937c4d.png)

Version 4
![IMG_4840](https://user-images.githubusercontent.com/2129013/98224201-7d4ee080-1f53-11eb-9355-4a666968d171.png)
![IMG_4838](https://user-images.githubusercontent.com/2129013/98224198-7c1db380-1f53-11eb-87e7-77a422de356d.png)
![IMG_4839](https://user-images.githubusercontent.com/2129013/98224200-7d4ee080-1f53-11eb-804d-c05e0d2074a9.png)

**Comment by SeydX** [comment]
@bkonings 

Tried to force close home app and reopen it again to refresh the tv accessory?

**Comment by bkonings** [comment]
> @bkonings
> 
> Tried to force close home app and reopen it again to refresh the tv accessory?

Seems the issue was that on V3 I named my tv "Sony TV" in the home app, in the new v4 I named the TV "Sony TV" in the configuration. Naming it "MyTV" resolved the issue.
