### ISSUE TITLE
ERROR:{"error":[15,"power on not supported"],"id":1}

### ISSUE THREAD

**Issue by OkiRules** [SeydX/homebridge-bravia-tvos#9]
Is this an error from the plugin or my tv. I have remote start on.

**Comment by SeydX** [comment]
Which model u have? It seems that your tv doesnt support this kind of commands

**Comment by OkiRules** [comment]
DS415+

Thanks,
Oscar

**Comment by SeydX** [comment]
thats not your tv model or?? which tv model u have?

**Comment by OkiRules** [comment]
Sorry that was my ds model. The TV model is KDL-70W850B

Thanks,
Oscar

**Comment by SeydX** [comment]
Is this a android tv?

**Comment by OkiRules** [comment]
It might be how do I tell?

Thanks,
Oscar

**Comment by SeydX** [comment]
Googled for it and yes its not an android tv. This plugin only supports sony tvs with android interface, closing

**Comment by OkiRules** [comment]
Wait a sec.. so what plugin should I install?
