### ISSUE TITLE
Channels conflict

### ISSUE THREAD

**Issue by sch115** [SeydX/homebridge-bravia-tvos#92]
When I set list of dvbt channels 1 - 20, everything is listed in home app without issue. But than no matter how I change the numbering in the TV itself, after choosing channel 1 it jumps directly onto channel 10. Any idea? Thanks!

**Comment by SeydX** [comment]
@sch115 

`But than no matter how I change the numbering in the TV itself, after choosing channel 1 it jumps directly onto channel 10 `

You mean if you choose a channel via HomeKit the TV opens channel 10 instead of channel 1? That occurs also with other channels? Is it always channel 10 or..?

**Comment by sch115** [comment]
Exactly! All the other channels work fine (not 100% sure about channel 2 to 20, have to check again). The channel num. 1 even loads his exact name from TV but once you scroll on it through Homekit icon than the TV switches to channel 10. I've tried to change the numbering in TV setup to start counting from 2 etc but it didn't help.

**Comment by SeydX** [comment]
@sch115 

should be fixed with v4.0.8

**Comment by sch115** [comment]
Thank you!!! At the end, just in case anybody else is going to have same issues, I've had to re-tune whole TV to get new list of channels. I believe there was (in TV) some cached information causing this bug. After this I was able to input all the channels I wanted to have in Homekit and everything is working like a charm now.
