### ISSUE TITLE
command:  bravia pair <host> -p 80 -n MyTV -t 5 or bravia pair <host> -p 80 -n MyTV -t 10 not working

### ISSUE THREAD

**Issue by czarnyolek** [SeydX/homebridge-bravia-tvos#93]
Hello
I have bravia without Android. To plugin version 3.0.7 plugin worked perfect. TV paired with PSK
Now have problem becouse I dont have list with inputs: Hdmi1, Hdmi2, Hdmi3 and HDmi4, also after turn off TV - when some time has passed - TV with HB is not a pair - must restart HB when TV is on. 

When TV is not pair with HB I  see this log in console:

[11/12/2020, 4:26:14 PM] [BraviaTVOS] Bravia: Can not reach TV!
2020-11-12T15:26:18.118Z ciao:Responder Sending response via unicast to {"address":"192.168.1.119","port":5353,"interface":"eth0"} (took 2 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 987B (UPS: 1440)
[11/12/2020, 4:26:27 PM] [BraviaTVOS] Bravia: ON
[11/12/2020, 4:26:27 PM] [BraviaTVOS] Bravia: Can not reach TV!
[11/12/2020, 4:26:27 PM] [BraviaTVOS] Bravia: An error occured during powering on tv!
[11/12/2020, 4:26:27 PM] [BraviaTVOS] Error: connect EHOSTUNREACH 192.168.1.46:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.46',
  port: 80,
  config: {
    url: 'http://192.168.1.46:80/sony/system',
    method: 'post',
    data: '{"id":3,"method":"setPowerStatus","version":"1.0","params":[{"status":true}]}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'text/xml; charset=UTF-8',
      SOAPACTION: '"urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"',
      'X-Auth-PSK': 'lipsum555',
      'User-Agent': 'axios/0.21.0',
      'Content-Length': 77
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 5000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Array],
      error: [Function: handleRequestError],
      timeout: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/sony/system',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.1.46',
      port: '80',
      nativeProtocols: [Object],
      pathname: '/sony/system'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 77,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /sony/system HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: text/xml; charset=UTF-8\r\n' +
        'SOAPACTION: "urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"\r\n' +
        'X-Auth-PSK: lipsum555\r\n' +
        'User-Agent: axios/0.21.0\r\n' +
        'Content-Length: 77\r\n' +
        'Host: 192.168.1.46\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/sony/system',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.1.46',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.1.46:80/sony/system',
    _timeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 8025949,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 19600,
      [Symbol(triggerId)]: 19596
    },
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[11/12/2020, 4:26:40 PM] [BraviaTVOS] Bravia: Can not reach TV!
[11/12/2020, 4:26:53 PM] [BraviaTVOS] Bravia: Can not reach TV!

I think problem is with PSK pairing, and now I try pair with token. But how I must pairing?
what should the pairing command look like?
the instructions show that it should look like bellow:
bravia pair 192.168.1.46 -p 80 -n BRAVIA -t 10

When I paste this command: 
bravia pair 192.168.1.46 -p 80 -n BRAVIA -t 10
or
bravia pair 192.168.1.46 -p 80 -n BRAVIA -t 5

I have this result in terminal:

bash: pair: command not found

Can you help please?

**Comment by SeydX** [comment]
@czarnyolek 

the error has nothing to do with pairing. You can just use your PSK in your config.

The problem is, that your tv can not be reached when it is off and some time has passed.

You could try to enable "wol" in your config to avoid turning on the TV via API. To be enable to turn on the TV via WOL, it must be activated also on your TV

**Comment by czarnyolek** [comment]
I understand, but until version 3.0.7 there was no problem. Now when I come back to this version there is this problem as well

ps. "wol" in config what is responsible for? And what is the function of TV?

**Comment by SeydX** [comment]
API only works when the TV is on or in STANDBY mode.

Some older TVs will immediately switch to OFF instead of STANDBY. Therefore the API is not accessible.

The WOL method bypasses this and sends packets to the TV to wake it up. When the TV is turned ON, the plugin works as intended.

**Comment by idominiki** [comment]
I can‘t use the Bravia pair command, too. Also if I ran the command inside the node modules folder. 

Output: bravia: command not found
Also when TV is on

**Comment by SeydX** [comment]
@czarnyolek @idominiki 

do you have installed the latest bravia module?

``sudo npm i -g @seydx/bravia@latest --unsafe-perm``

**Comment by idominiki** [comment]
I think so but it seems I didn't; worked now!
