### ISSUE TITLE
ARC audio choice

### ISSUE THREAD

**Issue by paqpaqpaq** [SeydX/homebridge-bravia-tvos#94]
Would it be possible to choose which audio channel the TV should use?
e.g. 

Apple TV > HDMI audioset > ARC out to ARC TV. (HDMI 4)

If the TV is set to TV speakers, it will mute the audioset as default. 
If the TV is set to HDMI ARC, it will work via the audioset.

**Comment by SeydX** [comment]
Hm sry for the dump question but what u mean exactly :D

**Comment by paqpaqpaq** [comment]
Sorry for my late reply.

I mean this setting:

![IMG_3113-2](https://user-images.githubusercontent.com/34166264/99669779-df3d3900-2a6f-11eb-8528-649ee70b76ea.jpg)
![IMG_3114-2](https://user-images.githubusercontent.com/34166264/99669805-e95f3780-2a6f-11eb-91e7-be9bd980116d.jpg)

**Comment by SeydX** [comment]
@paqpaqpaq 

Ah, i will check this thanks

**Comment by Fofer** [comment]
Yes, same request here.  Often my Bravia's speaker setting gets changed to TV speaker (I'm not sure why) and I have to use the Sony remote to get to Settings to change it to ARC. So if there could be a shortcut button for this in HomeKit, that would be amazing.

**Comment by SeydX** [comment]
Added in v4.1.2

You can now create macros. I have added two macros to example config that show how to switch between these two settings.

[Example Config](https://github.com/SeydX/homebridge-bravia-tvos/blob/master/example-config.json#L69)

**Comment by paqpaqpaq** [comment]
Cool, thanks.
I did change my hardwired setup with regards to HDMI ARC and have it 'solved' that way, but actually this is a quite welcome feature to have!
