### ISSUE TITLE
Inputs Unsynced after Update

### ISSUE THREAD

**Issue by proactivematter** [SeydX/homebridge-bravia-tvos#95]
Hello,

Out of all the add-ons I have, this one is the only one that has been completely reliable. However, after the latest update, my inputs no longer work correctly. That is, "HDMI1, HDMI2, etc" as well as Apps "YouTube, Twitch etc" no longer take me to the correct input, instead they take me to something else entirely that I may not even have listed as an input in the addon.

HDMI 3 takes me to Sony Music app. HDMI 4 takes me to HDMI 3. Youtube is taking me to cable TV.

Logs are clean. Please advise. Thank you.

**Comment by SeydX** [comment]
Hm it seems that the plugin sets wrong identifier to the inputs.

The same issue also with channels
#92 

I will look into this, thanks for reporting

**Comment by SeydX** [comment]
@proactivematter 

After changing input, is the name correct from target in log?

There must be something like

``Changing input source to YouTube``

**Comment by proactivematter** [comment]
Oh wow, sorry I had only looked for errors, it didn't occur to me to check that.

Yes, the logs show the actual input I am getting switched to.

**Comment by SeydX** [comment]
@proactivematter 

So name is correct but it takes you to wrong input? Hmm

**Comment by proactivematter** [comment]
Sorry, I thought I had phrased it well.

The name shown on the log is the ACTUAL input that my TV is changing to, not the one it should be changing to.

i.e. If I select HDMI3 on Apple Home, it takes me to "Music". The logs then show: "Sony: Changing application to Music".

**Comment by SeydX** [comment]
@proactivematter 

I can not reproduce it. Can u please set „refreshInputs“ to true in config and restart homebridge. Maybe this will fix it

**Comment by proactivematter** [comment]
I tried that to no avail, but... I did notice this on the log. I guess it may have been there before, but as it wasn't red I didn't take notice. Sorry, I am not a dev and thought errors would always show in red. I think this will point you in the right direction:

[11/12/2020, 8:55:41 PM] [BraviaOSPlatform] Sony: "refreshInputs" setted to false!
(node:95002) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'YouTube' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at /usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:688:47
    at Array.forEach (<anonymous>)
    at tvAccessory.configureInputSources (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:666:40)
    at tvAccessory.getService (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:72:16)
(node:95002) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95002) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SeydX** [comment]
@proactivematter 

Can u set „refreshInputs“ to true, restart homebridge and send me the whole log pls

**Comment by proactivematter** [comment]
Done. Noticed an error, as evidenced below. My homebridge says v1.1.6 is the latest though...?

[11/12/2020, 9:14:48 PM] Got SIGTERM, shutting down Homebridge...
[11/12/2020, 9:14:53 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/12/2020, 9:14:58 PM] [HB Supervisor] Restarting Homebridge...
[11/12/2020, 9:14:58 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/12/2020, 9:14:58 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 96577
[11/12/2020, 9:14:59 PM] Loaded config.json with 0 accessories and 6 platforms.
[11/12/2020, 9:14:59 PM] ---
**[11/12/2020, 9:14:59 PM] The plugin "homebridge-bravia-tvos" requires a Homebridge version of ^1.2.0 which does not satisfy the current Homebridge version of 1.1.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.**
[11/12/2020, 9:15:02 PM] [BraviaOSPlatform] Initializing BraviaOSPlatform platform...
[11/12/2020, 9:15:02 PM] [BraviaOSPlatform] Sony: Configuring accessory...
[11/12/2020, 9:15:08 PM] [BraviaOSPlatform] Sony: "refreshInputs" setted to false!
(node:96577) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'YouTube' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at /usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:688:47
    at Array.forEach (<anonymous>)
    at tvAccessory.configureInputSources (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:666:40)
    at tvAccessory.getService (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:72:16)
(node:96577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:96577) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SeydX** [comment]
@proactivematter 

Is your tv displayed as TV in home app?

**Comment by proactivematter** [comment]
On my MAC running Catalina, yes, it shows as a TV with a TV icon. On my iPhone, after updating to iOS14, it shows a generic "house" icon, though as far as I can tell everything functions the same.

**Comment by SeydX** [comment]
@proactivematter 

Can u please remove the TV from Apple Home, rename it in config.json and restart homebridge pls

You need to add it again to Apple Home via „Add Accessory“ in Home. The Pin is printed in the Log

If the Inputs shown as seperat accessories, force close apple home and re open

Then try again switching inputs pls

**Comment by proactivematter** [comment]
OK, I couldn't find a way to remove just the TV, so I removed the bridge itself and added it back.

I renamed the TV from "Sony" to "X900F".

I added the bridge back and all acessories came back online, but the TV didn't.

The log shows the following:

`[11/12/2020, 10:21:54 PM] [BraviaOSPlatform] X900F: An error occured during fetching tv:analog, skip..`

**Comment by SeydX** [comment]
@proactivematter 

You can ignore that.

As i said, you need to add the tv like a bridge with a pin to homekit

**Comment by proactivematter** [comment]
Got it! OK, everything working as it should now. Pretty cool that CEC now returns the name of my devices instead of just HDMI1/2/3 etc. Thank you so much for the help and patience @SeydX !

Just one minor thing I would like to ask - is there a way to have CEC inputs be listed first? Currently apps are listed first, and then CEC.

**Comment by SeydX** [comment]
Wonderful

I didnt figure out how apple handles the display order atm. But im on it, maybe in a future version there will be a option to customize the display order via config

Closing the issue now :)

**Comment by SeydX** [comment]
@proactivematter 

DisplayOrder added in v4.0.8

See [Example Config](https://github.com/SeydX/homebridge-bravia-tvos/blob/b4a5ff6c1fa65e35a1797f1899e362f2ff43922d/example-config.json#L66)

____

### DisplayOrder works like below

_Example_
```
// 1) Order in Apple Home: 1. Inputs, 2. Applications, 3. Channels, 4. Commands

...
"displayOrder": [
  "inputs",
  "apps",
  "channels",
  "commands"
]
...


// 2) Order in Apple Home: 1. Channels, 2. Commands, 3. Channels, 4. Inputs

...
"displayOrder": [
  "channels",
  "commands",
  "channels",
  "inputs"
]
...

```


### If you want to sort eg. apps one by one, just rearrange the apps inside the array

_Example_
```
// 1) Order in Apple Home: 1. Youtube, 2. Netflix, 3. Prime Video

...
"apps": [
  "YouTube",
  "Netflix",
  "Prime Video"
]
...

// 2) Order in Apple Home: 1. Prime Video, 2. Netflix, 3. YouTube

...
"apps": [
  "Prime Video",
  "Netflix",
  "YouTube"
]
...
```

**Comment by proactivematter** [comment]
Awesome @SeydX! Got it set up just the way I want it! Thank you 🙂
