### ISSUE TITLE
An error occured during polling tv/speaker state

### ISSUE THREAD

**Issue by idominiki** [SeydX/homebridge-bravia-tvos#96]
Sorry SeydX; but now I have the same error with the bravia-tvOS plugin.
![Bildschirmfoto 2020-11-14 um 12 22 18](https://user-images.githubusercontent.com/62521486/99145988-0e206d00-2674-11eb-9e55-5001e17fd15b.png)

**Comment by SeydX** [comment]
@idominiki 

Can u turn on debug pls in config and restsrt homebridge

**Comment by idominiki** [comment]
![50766D80-03E2-4088-9201-48B381AB884F](https://user-images.githubusercontent.com/62521486/99190069-c4637f80-2764-11eb-924f-54d7a69797cd.jpeg)
Here with debug enabled

**Comment by idominiki** [comment]
If I turn on the TV everything works fine. No errors

**Comment by SeydX** [comment]
@idominiki 

This is an log bug, normally it ist a error, it says just that the tv is turned off

With next version i will remove it from the log

Any other errors? Otherwise this can be closed or?

**Comment by idominiki** [comment]
Thanks for your great work!
