### ISSUE TITLE
Pin

### ISSUE THREAD

**Issue by frieder732** [SeydX/homebridge-bravia-tvos#97]
Hello, where do I have to use this command to get the token.
bravia pair <host> -p 80 -n MyTV -t 5

**Comment by SeydX** [comment]
hey @frieder732 

open terminal and write the command

or wait for next version

![braviatvos_ui_demo](https://user-images.githubusercontent.com/34152761/99849975-ce2e1e00-2b7c-11eb-8382-2933e68004c2.gif)

**Comment by SeydX** [comment]
Added in v4.1.0
